### PR TITLE
feat(files): download files implementation

### PR DESCRIPTION
**Pull request by Jekrimo**
**What this PR does** 📖
Adds link to enable downloading shared files

**Which issue(s) this PR fixes** 🔨
AP-299

**Additional comments** 🎤
I thought about leaving in all the textile work but since it wasn't exactly functional anyway decided to keep it small and simple.

### CODE REVIEW

**Review by stavares843 — CHANGES_REQUESTED** [review]
I see the download icon

Captura de ecrã 2021-12-29, às 17 06 30

and works

but only for files

is this supposed to work for images as well?

Captura de ecrã 2021-12-29, às 17 06 43

and I couldn't see a downloading indicator, it downloads the file locally and no downloading indicator, is there a specific flow to trigger the downloading indicator?

the ticket JIRA says ''Implement download button / Show downloading indicator''

**Comment by Jekrimo** [comment]
> how downloading indicator

I assumed the indicator was just the spinner load on the cursor which I got automatically. Searching through the repo I don't see a downloading indicator or anything, maybe it would be an alert or something but it auto shows in browser that it's downloading so seems redundant?

And yes, no dl icon for files, users can click and drag or ctrl save as I assume.

**Comment by WanderingHogan** [comment]
I am very sorry - can you make the file download and image download embeds look like this mockup:

image

Can you make the highlight colors use @RetroPronghorn 's new theming work, and update the ticket to reflect this

**Comment by Jekrimo** [comment]
Completed! Took me absolutely forever to find how to dl an image and not open in a tab automatically. Absolutely infuriating. But should be good to go! Accidentally pushed to AP-285 first hence the force push here.

**Comment by stavares843** [comment]
neat, thanks! 💥 checking 🔨

**Comment by stavares843** [comment]
Captura de ecrã 2022-01-03, às 21 14 06

Captura de ecrã 2022-01-03, às 21 14 26

neat 🎉

**Comment by Jekrimo** [comment]
> Captura de ecrã 2022-01-03, às 21 14 06
> 
> Captura de ecrã 2022-01-03, às 21 14 26
> 
> neat 🎉

OHHHHH I didn't try the yellow, prettyyyyyyy

**Comment by stavares843** [comment]
haha yes 🎨

**Comment by stavares843** [comment]
https://user-images.githubusercontent.com/29093946/147981592-94fbcf09-4a7f-49b7-9723-d368f0b78aa7.mp4

i noticed some file types download to a file, but some open on a separate tab, do you know why/is this expected behavior/will be rectified later?

**Comment by stavares843** [comment]
Captura de ecrã 2022-01-03, às 21 23 30

on mobile if the filename is a bit big, gets cut off on mobile

third file from the list above

**Comment by stavares843** [comment]
Captura de ecrã 2022-01-03, às 21 25 15
Captura de ecrã 2022-01-03, às 21 25 30

i also noticed that on mobile, on images, the download button is not on the message section relevant to the image row, if you hover, the download appears on the message below, in this case the glyph

on desktop is fine

**Comment by Jekrimo** [comment]
> Screen.Recording.2022-01-03.at.9.19.44.PM.mp4 
> i noticed some file types download to a file, but some open on a separate tab, do you know why/is this expected behavior/will be rectified later?

Wooooooahhhhh. That's weird. Yeah we should make a tickets for those file types, I think it'll be an easy fix but not sure

**Comment by stavares843** [comment]
sounds good, will add 💥

**Comment by Jekrimo** [comment]
> Captura de ecrã 2022-01-03, às 21 25 15
> 
> Captura de ecrã 2022-01-03, às 21 25 30
> 
> i also noticed that on mobile, on images, the download button is not on the message section relevant to the image row, if you hover, the download appears on the message below, in this case the glyph
> 
> on desktop is fine

craps, lemme look into it

**Comment by Jekrimo** [comment]
> Captura de ecrã 2022-01-03, às 21 25 15
> 
> Captura de ecrã 2022-01-03, às 21 25 30
> 
> i also noticed that on mobile, on images, the download button is not on the message section relevant to the image row, if you hover, the download appears on the message below, in this case the glyph
> 
> on desktop is fine

image
My mobile is super jacked lol idk what's up with it. But. I updated the dl to stay in the same box so it doesn't crop out, but it moves it to be aligned to the top on mobile, which honestly I don't hate so I left it.

**Comment by stavares843** [comment]
Captura de ecrã 2022-01-04, às 00 37 11

i did git pull and started a new server but im still seeing the download on the glyph row 💥

**Comment by Jekrimo** [comment]
> Captura de ecrã 2022-01-04, às 00 37 11
> 
> i did git pull and started a new server but im still seeing the download on the glyph row 💥

Fixed! Thank you for your patience!

**Comment by stavares843** [comment]
fixed 🎉

**Comment by stavares843** [comment]
Captura de ecrã 2022-01-04, às 16 04 34

can we add a bit more padding between the download button and the icon and vertically center image filename with the image icon?

to be more similar with the design

minor things

**Comment by Jekrimo** [comment]
> Captura de ecrã 2022-01-04, às 16 04 34
> 
> can we add a bit more padding between the download button and the icon and vertically center image filename with the image icon?
> 
> to be more similar with the design
> 
> minor things

100% good catch thank you! Updated!

**Comment by stavares843** [comment]
thanks 🎉

**Comment by stavares843** [comment]
Captura de ecrã 2022-01-04, às 17 35 35
Captura de ecrã 2022-01-04, às 17 35 25

other thing I noticed on hogan's design screenshot was when hovering the whole row, it has more padding around the image and the download option

is this something that should be addressed on other PR?

Captura de ecrã 2022-01-04, às 17 35 13

minor thing on the alignment, the icon filetype is not fully aligned with the subtitle below

**Comment by Jekrimo** [comment]
> 

What's up eagle eye! Got that fix up, added a little bit of patting for the container, may want a specific ticket to address it though as I think it may need some tlc across all message types.

**Comment by stavares843** [comment]
neat, thanks for fixing! 🎉

**Review by stavares843 — APPROVED** [review]

**Review by WanderingHogan — APPROVED** [review]

**Pull request merged**
