### PR TITLE
feat(createAccount): better error messages/handling on username error

### PR DESCRIPTION
**Pull request by josephmcg**
**What this PR does** 📖
- add red border around username while invalid after a user failed submission once
- make error message update along with our Config values (groups and accounts)
- remove unused data

**Which issue(s) this PR fixes** 🔨
AP-1741

**Special notes for reviewers** 🗒️
Is the native error better regarding accessibility?
image

**Additional comments** 🎤

### CODE REVIEW

**Review by jasonwoodland — APPROVED** [review]

**Review by molimauro — APPROVED** [review]

**Comment by molimauro** [comment]
> I moved preventDefault lower so the browser error message wouldn't come through. Not sure how we feel about it. Is the native error better regarding accessibility?

Its fine for now :)

**Comment by josephmcg** [comment]
But thats not a new issue, thats the way it's always behaved. If you want to change that, it should be in a separate ticket

**Comment by molimauro** [comment]
oh its the `preventDefault` i guess

**Comment by josephmcg** [comment]
Sara and I discussed. I didn't fully understand the issue. will fix tomorrow

**Comment by josephmcg** [comment]
@stavares843 should be better now

**Comment by stavares843** [comment]
thanks @josephmcg 🔨

**Review by stavares843 — APPROVED** [review]

**Pull request merged**
