### PR TITLE
feat(chat): unread message indicators

### LINKED ISSUE #5002: Unread message banner in chat
image

### PR DESCRIPTION
**Pull request by jasonwoodland**
### What this PR does 📖
- Adds top and bottom unread message indicator to chat when new messages aren't visible in the viewport

### Which issue(s) this PR fixes 🔨
- Resolve #5002

### CODE REVIEW

**Review by nathan-power — CHANGES_REQUESTED** [review]
Looks good, just a couple things that stand out:
- "New Messages" tag doesn't get updated to the new unread messages position.
https://app.usebubbles.com/g5fJNo1r4UiVZAR9UdR8qx/my-video-recording?threadId=ekRFR3v3EZ4eKWFTiSBfa9

- Might be nice to give the chat bar component sharp top corners when the blue unread banner is positioned directly above it, like how it is in the chat when file previews are shown.
example

**Comment by jasonwoodland** [comment]
@nathan-power
> "New Messages" tag doesn't get updated to the new unread messages position.

Fixed

> Might be nice to give the chat bar component sharp top corners when the blue unread banner is positioned directly above it, like how it is in the chat when file previews are shown.

Not sure how to make this look good since it has a transition, so leaving for now

**Review by nathan-power — CHANGES_REQUESTED** [review]
Looking good! Just one small thing, messages aren't marked as read upon opening the message. The chat has to be scrolled up and then down before the messages are marked as read. After that's fixed it should be all good to merge 👍

**Review by stavares843 — COMMENTED** [review]
Captura de ecrã 2022-10-03, às 00 41 25


i made 2 account, sent 100 messages from user A to user B, user B never opened the chat before, and then when opening, the badge in the sidebar says 99+ unread but the banner says 50

**Comment by jasonwoodland** [comment]
@stavares843 Good spot, should be fixed now 😁

**Comment by jasonwoodland** [comment]
@nathan-power should be fixed

**Comment by jasonwoodland** [comment]
self lgtm

**Review by josephmcg — APPROVED** [review]

**Pull request merged**
