### PR TITLE
fix(settings): remove unnecessary items AP-653

### PR DESCRIPTION
**Pull request by davidchan1219**
**What this PR does** 📖

remove unnecessary items 

**Which issue(s) this PR fixes** 🔨

AP-653

### CODE REVIEW

**Comment by phillsatellite** [comment]
Hi David! Tested and seems like the Account Identifier is still showing on the profile page. All I could find so far 🔨 
profile

**Comment by davidchan1219** [comment]
@phillsatellite I've just removed the account identifier part.

**Review by WanderingHogan — APPROVED** [review]

**Review by phillsatellite — APPROVED** [review]

**Comment by stavares843** [comment]
Captura de ecrã 2022-02-02, às 22 00 53

if we removed the account info data, maybe we don't need the account info title/subtitle

**Comment by stavares843** [comment]
@WanderingHogan let me know if you agree and i can add a ticket

merging

**Pull request merged**
