### PR TITLE
fix(register): submit form on enter

### PR DESCRIPTION
**Pull request by AlexZakablukov**
**What this PR does** 📖
submit create user form on enter

**Which issue(s) this PR fixes** 🔨
[AP-1130](https://satellite-im.atlassian.net/browse/AP-1130)

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

### CODE REVIEW

**Review by WanderingHogan — APPROVED** [review]

**Comment by phillsatellite** [comment]
Tested: Hi Alex! only one little thing, space is being counted as a char, so if I make my username "Phil *space bar*" it will recognize it as a 5 char name. Is this intended? 

https://user-images.githubusercontent.com/93608357/159525572-36cab992-c017-470a-81e1-cea0344d88a5.mov

**Comment by WanderingHogan** [comment]
@phillsatellite does the account name get created with a space on the end?

**Comment by WanderingHogan** [comment]
@stavares843 ohh good eye

**Comment by WanderingHogan** [comment]
@stavares843 @phillsatellite updated

**Review by phillsatellite — APPROVED** [review]

**Comment by stavares843** [comment]
Captura de ecrã 2022-03-22, às 20 22 26

shows like this

**Review by phillsatellite — APPROVED** [review]

**Comment by stavares843** [comment]
testing again

**Comment by WanderingHogan** [comment]
i just checked on netlify and it looks okay now, i wonder why you saw the merge conflict text

**Review by stavares843 — CHANGES_REQUESTED** [review]
https://user-images.githubusercontent.com/29093946/159590449-4dcc4710-dca6-40a5-a053-c83b161ebcab.mov

if you just do enter, it shows the username has to have 5 chars error and then reloads by itself

**Comment by stavares843** [comment]
https://github.com/Satellite-im/Core-PWA/pull/2447#pullrequestreview-917983809

still happens, same flow

**Review by stavares843 — APPROVED** [review]

**Pull request merged**
