### PR TITLE
Dev tools settings

### PR DESCRIPTION
**Pull request by RetroPronghorn**
**What this PR does** 📖
This PR adds a section for information the user can use when including bug reports. Additionally it fixes a small issue with message reactions not being bound properly to light up when you're the one who reacted.

### CODE REVIEW

**Review by josephmcg — APPROVED** [review]
Reaction color + info page look good

**Comment by josephmcg** [comment]
Are these supposed to be pulling from locales or just placeholder?
image

**Comment by stavares843** [comment]
same question from above

pretty neat 🎉

**Review by stavares843 — APPROVED** [review]

**Comment by RetroPronghorn** [comment]
@stavares843 @josephmcg associated lang PR. thanks for the heads up I totally forgot!

**Pull request merged**
