### PR TITLE
feat(search): better search results pagination counter and timestamps

### PR DESCRIPTION
**Pull request by josephmcg**
**What this PR does** 📖
- results count that reflects current page, rather than just the total result count
- translations for a variety of results (0,1,multipage)
- fix pagination color w/ moonless night theme
- rework styles to be easier to read, concise, closer to figma
- add timestamps to search results (they update every minute)

**Which issue(s) this PR fixes** 🔨
AP-1328

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

### CODE REVIEW

**Comment by phillsatellite** [comment]
Tested: When I copy/send the current link "http://localhost:3000/#/chat/direct/DGTD1KvC2mDDebvzJ1V8NrVZRs8FTTQCpiPy7A9hehd9" and search for that in search bar it will show all of the messages sent/received in chat. When I tested this on dev branch it would crash 

https://user-images.githubusercontent.com/93608357/161587803-6449cf4c-5674-43ca-bdc6-eb100797a9ef.mov

**Review by phillsatellite — APPROVED** [review]

**Comment by stavares843** [comment]
Captura de ecrã 2022-04-06, às 18 40 32
Captura de ecrã 2022-04-06, às 18 40 39



is there a reason why 1 result doesn't have () and 2 or more results displays as (2)?

**Comment by stavares843** [comment]
minor question above, merging

**Review by stavares843 — APPROVED** [review]

**Comment by josephmcg** [comment]
no reason in particular, will be easy to change if we want to

**Pull request merged**
