### PR TITLE
feat(jest): 100% coverage for utilities/chat

### PR DESCRIPTION
**Pull request by drepram**
**What this PR does** 📖

Increase coverage for two untested cases.

**Which issue(s) this PR fixes** 🔨

AP-2247

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

### CODE REVIEW

**Review by stavares843 — APPROVED** [review]

**Review by josephmcg — APPROVED** [review]
going to approve because it doesn't hurt. but an object is always truthy, this doesn't really test anything

**Comment by stavares843** [comment]
@josephmcg let us know what we should address there and we can address your comments on a new PR considering this one was already merged 🔨

**Comment by josephmcg** [comment]
I'd say check object values specifically since objects are always truthy

image

**Comment by josephmcg** [comment]
oh im sorry, I was totally reading it incorrectly. this works fine

**Comment by josephmcg** [comment]
would avoid casting as 'any' as a rule of thumb, especially if we know the type (boolean in this case)

**Comment by stavares843** [comment]
😂 

thanks @josephmcg 🔨

**Pull request merged**
