### PR TITLE
feat(typingIndicator): add typing indicator on groupchat

### PR DESCRIPTION
**Pull request by nickjjang**
**What this PR does** 📖
Typing indicator on groups

**Which issue(s) this PR fixes** 🔨
AP-1379

### CODE REVIEW

**Review by pavlzk — APPROVED** [review]

**Comment by phillsatellite** [comment]
Tested: Works on Chrome very well but it seems to only appear in brave and safari if a Chrome User is typing. When typing on Brave or Safari indicator will only appear on the chrome user account.  I tested 1on1 chats on those browsers and they worked fine issue seems to just be in group chats

https://user-images.githubusercontent.com/93608357/164725387-0f1ac0a3-c177-4ef8-b650-f21aa316b3f3.mov

.

**Comment by iltumio** [comment]
@stavares843 we can close this PR since the issue is going to be fixed in another one related to group calls

**Comment by stavares843** [comment]
thanks @iltumio 🔨

**Pull request closed without merging**
