### PR TITLE
fix(register): throw error on unscannable file type and block upload

### PR DESCRIPTION
**Pull request by AlexZakablukov**
**What this PR does** 📖
throw error on unscannable file type and block upload

**Which issue(s) this PR fixes** 🔨
[AP-959](https://satellite-im.atlassian.net/browse/AP-959)

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

### CODE REVIEW

**Review by josephmcg — CHANGES_REQUESTED** [review]
please dont make the nsfw function throw an error. we want to allow uploads if the filesystem if theyre too large to be scanned or an un-scannable type.

could you do something like this instead? including the valid types.
`<input type="file" name="myImage" accept="image/png, image/gif, image/jpeg" />`

**Comment by AlexZakablukov** [comment]
> please dont make the nsfw function throw an error. we want to allow uploads if the filesystem if theyre too large to be scanned or an un-scannable type.
> 
> could you do something like this instead? including the valid types. `<input type="file" name="myImage" accept="image/png, image/gif, image/jpeg" />`

Including valid types to input tag does not solve this issue, I can make mime type check before nsfw check

const mime = await mimeType(file) 
if(!mime){
  return 
}

something like this in Create.vue

**Comment by josephmcg** [comment]
I see, we may want to add it anyways just so the user doesn't try to upload an invalid type.

I made a utility function that could help with the file byte check
`isEmbeddableImage`
utilities/FileType.ts

**Comment by AlexZakablukov** [comment]
fixed

**Review by phillsatellite — APPROVED** [review]

**Review by josephmcg — APPROVED** [review]
thanks Alex, I appreciate your flexibility on this

**Pull request merged**
