### PR TITLE
fix(chat): fix disappearing of emojis

### PR DESCRIPTION
**Pull request by AlexZakablukov**
**What this PR does** 📖
fix disappearing of emojis

**Which issue(s) this PR fixes** 🔨
[AP-796](https://satellite-im.atlassian.net/browse/AP-796)

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

### CODE REVIEW

**Comment by stavares843** [comment]
fixed

**Review by stavares843 — APPROVED** [review]

**Review by KemoPaw — APPROVED** [review]
Works smoothly!

**Review by josephmcg — CHANGES_REQUESTED** [review]
I encountered a bug where emojis are blank

1. open glyphs
2. open emojis from the button inside the chatbar

image

**Comment by stavares843** [comment]
checking here 🔨

**Review by WanderingHogan — APPROVED** [review]

**Comment by AlexZakablukov** [comment]
fixed

**Review by stavares843 — CHANGES_REQUESTED** [review]
https://user-images.githubusercontent.com/29093946/154732858-31c634e8-e0ba-4591-805f-2445217ccb81.mov

if you jump to 7 seconds

was able to reproduce the issue again
Captura de ecrã 2022-02-18, às 17 30 08

**Comment by stavares843** [comment]
I think we should fix that later, is edge case - I mean my video.

**Review by stavares843 — APPROVED** [review]

**Review by WanderingHogan — APPROVED** [review]

**Pull request merged**
