### PR TITLE
fix(unit-test): add jest-canvas-mock

### PR DESCRIPTION
**Pull request by baymax-codecare**
**What this PR does** 📖
fix(unit-test): add jest-canvas-mock

**Which issue(s) this PR fixes** 🔨

AP-607

### CODE REVIEW

**Review by Jekrimo — APPROVED** [review]

**Comment by drepram** [comment]
The tests returned green, but perhaps there is a need to lint the test file (re-sort order of imports, use `const` rather than `let` as it is never reassigned). Other than that, all looks good to me :)

image

**Review by drepram — COMMENTED** [review]
said above ^

**Review by WanderingHogan — CHANGES_REQUESTED** [review]
please lint the test, per @drepram's request

**Comment by stavares843** [comment]
cc @baymax-codecare

**Comment by baymax-codecare** [comment]
> please lint the test, per @drepram's request

done! :)

**Review by WanderingHogan — APPROVED** [review]

**Comment by WanderingHogan** [comment]
@baymax-codecare thank you

**Review by stavares843 — APPROVED** [review]

**Pull request merged**
