### PR TITLE
fix(search): search component refactor

### PR DESCRIPTION
**Pull request by josephmcg**
**What this PR does** 📖
- refactor and simplify search
- move components to views/chat/
- comment out search functionalities that aren't ready
- swapped store for emit/props since its only involving 3 directly related components
- I removed a lot of the bells & whistles from search, but left in pagination.

**Which issue(s) this PR fixes** 🔨
AP-983

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

### CODE REVIEW

**Comment by stavares843** [comment]
Captura de ecrã 2022-03-30, às 16 38 13

sending ''.:-_'' and then searching for ''.:-_'' no results appear

**Comment by stavares843** [comment]
Captura de ecrã 2022-03-30, às 16 39 55

same when sending a * and searching for *

**Comment by WanderingHogan** [comment]
@stavares843 it's fine if nothing appears with weird symbols. Good find on the crash.

**Review by WanderingHogan — APPROVED** [review]
Thank you for refactoring this away from the huge files and into smaller components

**Comment by WanderingHogan** [comment]
@stavares843 if you can't crash this again, any other changes can go into another ticket

**Review by stavares843 — APPROVED** [review]

**Pull request merged**
