### PR TITLE
chore(upload): remove unused computed

### PR DESCRIPTION
**Pull request by WanderingHogan**
**What this PR does** 📖
I was going to rip out the last reference to the deleted hounddog helper, but saw activeFriend was wasn't actually used

**Which issue(s) this PR fixes** 🔨
n/a

**Special notes for reviewers** 🗒️

**Additional comments** 🎤
Should notice no difference in functionality

### CODE REVIEW

**Review by josephmcg — APPROVED** [review]
Thanks, i saw this too. not sure how it got added back. maybe a rebase mistake

**Review by stavares843 — CHANGES_REQUESTED** [review]
this branch
Captura de ecrã 2022-05-31, às 01 50 57

dev

Captura de ecrã 2022-05-31, às 01 51 17


not sure why but this branch if you receive a request, gets duplicated

**Comment by josephmcg** [comment]
that seems like an unrelated bug. all this does is remove an unused variable

**Comment by stavares843** [comment]
agree but I couldn't reproduce on dev so I added the comment 😂 

phil had this bug on dev now so I'm merging this

gonna add ticket

**Pull request merged**
