### PR TITLE
feat(markdown): added markdown preview in sidebar

### PR DESCRIPTION
**Pull request by vimercati-samir**
What this PR does 📖
Added markdown preview in sidebar (last message).

Which issue(s) this PR fixes 🔨
AP-1478

Special notes for reviewers 🗒️

Additional comments 🎤

### CODE REVIEW

**Comment by phillsatellite** [comment]
Only two things I could find that didnt show up correctly are Spoilers and underlined markdowns
underline
spoilers

**Comment by phillsatellite** [comment]
Also noticed it appears blank when using markdown "< >" I reached out to Mauro to see what should appear 
Screen Shot 2022-05-11 at 2 12 11 PM

**Comment by vimercati-samir** [comment]
All issues should be resolved in commit b46deed2a01a0062bf5850052a69995896506fd2

**Comment by molimauro** [comment]
Do we want to keep the emoji big as in the chatbar if the text contains only emojis?

**Comment by phillsatellite** [comment]
Found small little bug that I couldnt replicate on dev branch or test.satellite (I'll ask clayton to replicate bug so we can be sure its just this pr) but I noticed when sending messages from Chrome to Safari, Safari wouldnt update or receive the messages 

https://user-images.githubusercontent.com/93608357/168320693-3a5b621e-de4b-40b1-8688-a41d2d79a692.mov

**Comment by vimercati-samir** [comment]
> Do we want to keep the emoji big as in the chatbar if the text contains only emojis?

I already had increased the font size for this specific case, I increased it a little more in commit b069ec4a95e2e5d8a4556fc0b5e3a7fa7b8a7ef7 but we cannot keep it as big as the one in the chatbar because there is no space

**Review by phillsatellite — APPROVED** [review]

**Review by WanderingHogan — APPROVED** [review]
If we want bigEmoji if it's emojis by itself this is good. I created a ticket to move the emoji wrapper code into a utility for after EA since it gets re-used more than one place https://satellite-im.atlassian.net/browse/AP-1568

**Comment by stavares843** [comment]
thanks @WanderingHogan 🔨

**Review by stavares843 — CHANGES_REQUESTED** [review]
Captura de ecrã 2022-05-17, às 00 08 52

the bold preview is almost invisible, can we add that text on the preview on the sidebar as the same color as we do on the rest of the preview?

example

Captura de ecrã 2022-05-17, às 00 09 33

**Comment by vimercati-samir** [comment]
> Captura de ecrã 2022-05-17, às 00 08 52
> 
> the bold preview is almost invisible, can we add that text on the preview on the sidebar as the same color as we do on the rest of the preview?
> 
> example
> 
> Captura de ecrã 2022-05-17, às 00 09 33

resolved in commit d5cd06a2dbd97412fd9bce072d46c11836527043

**Review by molimauro — APPROVED** [review]

**Pull request merged**
