### PR TITLE
fix(manager): start iridium manager fix

### PR DESCRIPTION
**Pull request by maljuburi**
Adds a listener for the stopping event for IridiumManager. to fix an offline messages issue

### CODE REVIEW

**Comment by stavares843** [comment]
can you add a description pls? what is this aiming to fix? 🔨

**Comment by maljuburi** [comment]
opened another PR

**Comment by maljuburi** [comment]
reopened because we decided to release this with other fixes later.

**Comment by stavares843** [comment]
this PR is the exact same as the other one, closing

**Pull request closed without merging**
