### PR TITLE
feat(privacy): re-work how signaling servers are stored in config.ts, and allow the user to change their settings.

### PR DESCRIPTION
**Pull request by genie-magic**
**What this PR does** 📖
re-work how signaling servers are stored in config.ts, and allow the user to change their settings.

**Which issue(s) this PR fixes** 🔨

AP-1074

**Special notes for reviewers** 🗒️
- See console log for checking signaling urls

### CODE REVIEW

**Comment by WanderingHogan** [comment]
@genie-magic I don't think this is working as expected. Also after messing around with it, what about re-initializing instead of reloading?

**Comment by tooshel** [comment]
> > But we should actually hold off on this change. @iltumio yesterday told me his webrtc rewrite will do away with the webtorrent signaling servers entirely using libp2p relays
> 
> You mean our all work for web torrents have no meaning @WanderingHogan ?

@genie-magic I wouldn't say "no meaning" . . . . even if something isn't merged in we still learned something.

**Comment by genie-magic** [comment]
> @genie-magic I wouldn't say "no meaning" . . . . even if something isn't merged in we still learned something.

Yes.  You are right.

**Comment by WanderingHogan** [comment]
@genie-magic I am going to close this but leave the branch up, and we can re-visit after we see what @iltumio and @Jekrimo get in for libp2p. Sorry, but good job on this

**Pull request closed without merging**
