### PR TITLE
fix(GroupDisplay): fix bug in displaying group chats

### PR DESCRIPTION
**Pull request by Jekrimo**
**What this PR does** 📖

Fix displaying group chats under group tab

**Which issue(s) this PR fixes** 🔨

AP-997

### CODE REVIEW

**Review by stavares843 — CHANGES_REQUESTED** [review]
this PR is adding a bunch of cypress old things that were removed when i removed the submodule 🔨 

please revert those 💥

**Comment by Jekrimo** [comment]
> this PR is adding a bunch of cypress old things that were removed when i removed the submodule 🔨
> 
> please revert those 💥

awesome, thank you, got em!

**Comment by stavares843** [comment]
awesome, thanks @Jekrimo 🎉

**Comment by phillsatellite** [comment]
Tested: it appears!! 😄 When I tested on an actual mobile device though the groups will appear cut off
groups mobile

**Comment by Jekrimo** [comment]
> 

I think I found it, would you mind checking it out again? I've only got the dev tools on chrome to check mobile

**Review by phillsatellite — APPROVED** [review]

**Review by aewing — APPROVED** [review]

**Comment by molimauro** [comment]
Schermata 2022-03-21 alle 11 04 42

They appear now but i think we can improve the css part, without using tricks like -200px. @Jekrimo can you try to refactor the css a little bit and use flex for keeping the content centered, etc? Thanks!

**Review by WanderingHogan — APPROVED** [review]

**Review by stavares843 — APPROVED** [review]

**Pull request merged**
