### PR TITLE
feat(user): hide the users have no any message AP-116

### PR DESCRIPTION
**Pull request by davidchan1219**
**What this PR does** 📖

hide the users has no messages in the sidebar

**Which issue(s) this PR fixes** 🔨

AP-116

### CODE REVIEW

**Review by WanderingHogan — APPROVED** [review]

**Comment by WanderingHogan** [comment]
this works really nice

**Comment by phillsatellite** [comment]
Tested: Had that same issue has before if User A sends a friend request to User B and User B accepts it, they're profile will show up in the sidebar 

https://user-images.githubusercontent.com/93608357/152231157-b9d0c65b-ffcb-4099-a915-57be46671a56.mov

**Comment by WanderingHogan** [comment]
@phillsatellite good find

**Comment by davidchan1219** [comment]
@WanderingHogan @phillsatellite 
I've just fixed the issue you mentioned above.

**Comment by phillsatellite** [comment]
Retested: Issue above was fixed I did find one other small issue when retesting, in video you can see that User A sends User F a friend request, User F accepts it and starts to message User A. No matter how many messages they send, User F will not appear in User A's sidebar until User A responds to him. So it seems only conversations that the user replies to will appear in the sidebar.

https://user-images.githubusercontent.com/93608357/152376963-16414558-d97b-402b-9d6b-e847474d7f06.mov

**Comment by WanderingHogan** [comment]
@phillsatellite this is a different issue we will need to work through - unfortunately. We need to subscribe to updates through textile. We can dig into this on friday and create the tickets for it

**Review by phillsatellite — APPROVED** [review]

**Pull request merged**
