### PR TITLE
refactor(scroll): switch to lightweight css scroll rather than component

### PR DESCRIPTION
**Pull request by josephmcg**
**What this PR does** 📖
- remove scroll component in favor of css rules in various places
- remove unused css variables

**Which issue(s) this PR fixes** 🔨
AP-1878, AP-1862, AP-1857

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

### CODE REVIEW

**Review by WanderingHogan — APPROVED** [review]

**Comment by josephmcg** [comment]
gonna match confirmed requirements from Liz

**Comment by josephmcg** [comment]
new global styles interfere with instances of the current scroll component. the scope of this needs to be expanded

**Comment by josephmcg** [comment]
will be ready soon, waiting for jason's mobile user picker change to go through

**Comment by josephmcg** [comment]
blocked by https://github.com/Satellite-im/Core-PWA/pull/3825
will fix mobile styles after that goes through. has some changes that affects chat layout css

**Comment by josephmcg** [comment]
tried switching base to new iridium branch, but it's too involved. will need to be cherry picked and recreated. closing PR to clean up our list. don't delete branch because i need it to cherry pick

**Pull request closed without merging**
