### PR TITLE
refactor(chat): wrap image preview overlay in Modal component

### LINKED ISSUE #5153: wrap chat image preview modal in UiModal

### PR DESCRIPTION
**Pull request by josephmcg**
### What this PR does 📖
- better/more consistent background styles
- take advantage of esc listener to close modal
- 

### Which issue(s) this PR fixes 🔨
- Resolve #5153

### CODE REVIEW

**Review by stavares843 — COMMENTED** [review]
noticed something that happens on this PR but not on dev

image


if you send a image on chat > preview > click on left or right side will close the preview but if you click on the top/bottom doesn't close, on dev closes

**Comment by phillsatellite** [comment]
Hi Joe! 😄  A few little things I noticed on iOS I just wanted to share were, 

The consent files pop up had no background 

image

Another thing that I couldnt replicate on Dev was on IOS User could not upload an image because when they would give consent to file sharing the pop up would just keep re appearing 

https://user-images.githubusercontent.com/93608357/195149747-a88ea9d4-54ea-47c0-99e2-aab0841b06fe.mp4

**Comment by stavares843** [comment]
btw i didn't added the changes requested label to avoid blocking the PR

**Comment by josephmcg** [comment]
thanks, I'll check these out tomorrow

**Comment by josephmcg** [comment]
- universally applied modal styles rather than singularly in every modal. was using the wrong background color at the upper level
- fixed clickoutside issue on chat image overlay
- mobile issue seemed to resolve itself with the above changes

**Review by WanderingHogan — APPROVED** [review]

**Review by phillsatellite — APPROVED** [review]

**Pull request merged**
