### PR TITLE
feat(inputmultiple): allow user to paste recovery phrase into text input (AP-244)

### PR DESCRIPTION
**Pull request by nickjjang**
AP-244

### CODE REVIEW

**Review by stavares843 — CHANGES_REQUESTED** [review]
1 - when user copy pastes the string such as 

`boring over tilt regret diamond rubber example there fire roof sheriff always`

only goes to the next screen if user submits using the enter, the recover button is still deactivated
Captura de ecrã 2021-12-09, às 20 37 53

the ticket says, ''Once the user hits enter or the button to parse the pasted/typed in string''

Captura de ecrã 2021-12-09, às 20 39 47

2 - after clicking on enter, goes to this view

Captura de ecrã 2021-12-09, às 20 38 16


clicking on recover button doesn't do anything, no errors on console

3 - the layout on the create account is different from dev

this branch
Captura de ecrã 2021-12-09, às 20 32 17


dev
Captura de ecrã 2021-12-09, às 20 41 25

this layout modification wasn't requested on the ticket so needs to be reverted

**Review by WanderingHogan — APPROVED** [review]

**Comment by stavares843** [comment]
@nickjjang did you had a chance to check my feedback? thanks!

**Comment by nickjjang** [comment]
Hey @stavares843,
I noticed that Click recovery button to go to the view doesn't work but it is not addressed in this ticket. 
Will you report it new ticket?

**Comment by stavares843** [comment]
recover button is now working as well

**Pull request merged**
