### PR TITLE
fix(register): fix replace console error AP-326

### PR DESCRIPTION
**Pull request by davidchan1219**
**What this PR does** 📖

Fix replace console error

**Which issue(s) this PR fixes** 🔨

AP-326

### CODE REVIEW

**Review by phillsatellite — APPROVED** [review]

**Review by phillsatellite — APPROVED** [review]

**Comment by WanderingHogan** [comment]
When I try this branch, I get:
image
and
image
and I also did not see this error when switching back and testing creating an account on the dev branch. Did you verify this issue still existed?

**Comment by davidchan1219** [comment]
@WanderingHogan With new merge, that issue was fixed.

**Comment by stavares843** [comment]
this PR is empty

image

only has the Cypress submodule stuff

**Comment by stavares843** [comment]
also checked on dev and the error no longer happens

closing the PR

**Pull request closed without merging**
