### PR TITLE
fix(friends): remove friends on both sides

### PR DESCRIPTION
**Pull request by AlexZakablukov**
**What this PR does** 📖
remove friend on both client and ex friend sides by clicking on "remove friend" button

**Which issue(s) this PR fixes** 🔨
[AP-693](https://satellite-im.atlassian.net/browse/AP-693)

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

### CODE REVIEW

**Comment by phillsatellite** [comment]
Tested: Only two things I'm curious about, should this PR include the ability to remove friend by right clicking on them in the Sidebar

https://user-images.githubusercontent.com/93608357/153442715-d1a70619-01ab-488a-af6d-37591694354f.mov


other thing was when User B removes User A, User A can still see them on they're friends list until they refresh they're page. Is there a way to have them removed without the user having to refresh they're page? 

https://user-images.githubusercontent.com/93608357/153442825-cf346c28-0af3-448b-9fb8-caad4065d22e.mov

**Comment by stavares843** [comment]
very good points 🔨 

both should be addressed

**Comment by AlexZakablukov** [comment]
I add feature to remove friend from sidebar, make simple loading while it removing, and fix remove from both sides

**Review by WanderingHogan — APPROVED** [review]

**Comment by stavares843** [comment]
after i tested what phil mentioned

''ability to remove friend by right clicking on them in the Sidebar''

it updates properly now, but when user A removes the user from the sidebar, crashes on the user B

Captura de ecrã 2022-02-11, às 16 49 58

so, this error was fixed previously [here](https://github.com/Satellite-im/Core-PWA/pull/740) in case thats useful

**Review by stavares843 — CHANGES_REQUESTED** [review]
added comment

**Comment by AlexZakablukov** [comment]
check it one more time please, I think it is fixed 

https://user-images.githubusercontent.com/38879804/154046629-a8565d66-0b18-430a-8ecf-d264264109e9.mp4

**Review by phillsatellite — APPROVED** [review]

**Comment by stavares843** [comment]
to be improved on another ticket

merging

**Review by stavares843 — APPROVED** [review]

**Pull request merged**
