### PR TITLE
fix(friends): send user to correct screen when "Add Friend" is pressed

### PR DESCRIPTION
**Pull request by nathan-power**
**What this PR does** 📖
- If user is on mobile and has no friends then default friends screen is the "Add Friend" screen.

**Which issue(s) this PR fixes** 🔨

AP-2237

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

### CODE REVIEW

**Comment by josephmcg** [comment]
gonna switch to router instead

**Comment by josephmcg** [comment]
if we use that same route names, then we can double it up for desktop too :)

**Comment by nathan-power** [comment]
> if we use that same route names, then we can double it up for desktop too :) desktop currently using store, but should use router

Should we do that for the desktop route in this PR as well?

**Comment by josephmcg** [comment]
nah separate is ok

**Pull request merged**
