### PR TITLE
fix(heic): better heic checking

### PR DESCRIPTION
**Pull request by josephmcg**
**What this PR does** 📖
- identify all types of heic in chat using utility function I setup in another PR. uses magicbytes package

**Which issue(s) this PR fixes** 🔨
AP-1077

**Special notes for reviewers** 🗒️
- tests were failing due to arrayBuffer issue with jsdom. Andre & I encountered a similar issue a few days ago. He had some ideas of how to fix it, I'll let him know

**Additional comments** 🎤
- this will not detect corrupted photos that have been converted since it reads the byte data. I want to improve type checking on upload in a separate PR

### CODE REVIEW

**Review by molimauro — APPROVED** [review]

**Comment by molimauro** [comment]
Thanks 🙏

**Comment by stavares843** [comment]
thanks 🔨

**Comment by phillsatellite** [comment]
Tested: All real Heic I used sent and were able to preview 💥  I noticed a couple very minor things though

1. When user loads into the chat, it takes a long time to buffer any .heic image that is already in chat

https://user-images.githubusercontent.com/93608357/161299987-dec76b76-97d3-4709-9374-f4b32197916d.mov

2. It takes a very long time to load the preview when selecting 8 images to send in bulk, I was thinking if we can't speed this up right now maybe we could add the same curser behavior that we have when a user is uploading a file in Files page 

Uploading Untitled.mov…

Uploading File curser

Screen Shot 2022-04-01 at 12 02 54 PM

**Comment by josephmcg** [comment]
I agree that the files preview could be improved, but that it outside the scope of this ticket. These changes don't affect any sort of image loading in chat. What you may be seeing is my other change (copy and save images) rebased into this branch

**Comment by stavares843** [comment]
thanks @josephmcg 🔨

**Review by stavares843 — APPROVED** [review]

**Pull request merged**
