### PR TITLE
chore(jest): update jest

### PR DESCRIPTION
**Pull request by stavares843**
**What this PR does** 📖

chore(jest): update jest

### CODE REVIEW

**Comment by WanderingHogan** [comment]
@stavares843 what are you trying to fix with this pull request?

A couple things:
- You are using an ubuntu image, but brew is a mac specific package manager
- if you want to update pnpm, after the corepack-enable, you could run a `corepack prepare pnpm@latest --activate`
- you might need to also update node - most of us run 16.17 (lts) - not sure what this image has, if you can't update node but it is still a recent enough version, your corepack prepare statement needs a version number instead of latest

**Comment by stavares843** [comment]
https://discord.com/channels/997540176488300544/997545570510061671/1011793146247655426

**Comment by stavares843** [comment]
> what are you trying to fix with this pull request?

the only goal with this PR was the fact Drew took a look at the Github action and he said the pnpm step was redundant so i removed it

**Comment by stavares843** [comment]
> You are using an ubuntu image, but brew is a mac specific package manager



yes but it also works on ubuntu

https://docs.brew.sh/Homebrew-on-Linux



Captura de ecrã 2022-08-24, às 14 31 06

**Comment by stavares843** [comment]
either way brew was removed, as Drew suggested because it was redundant with the corepack enabled 🔨

**Pull request merged**
