### PR TITLE
feat(filesPage): rework files page ui AP-603

### PR DESCRIPTION
**Pull request by josephmcg**
opened this because the submodules update was complicating rebase. wanted my original branch to stay in tact on the chance this got messed up.
https://github.com/Satellite-im/Core-PWA/pull/1193

**What this PR does** 📖
- rework files page UI
- use flex instead of floats for layout
- clean up css

**Which issue(s) this PR fixes** 🔨
AP-603

**Special notes for reviewers** 🗒️
- I'm not using the same icons as the mockup, should I rip them from Figma and add to our icon library?
- I noticed some global style inconsistencies between mockup and our app.
  - buttons and inputs are 34px height in mockup. in our app, buttons are 30px height, while inputs have 32px. I added temp styles to avoid problems while we reconcile this

**Additional comments** 🎤

### CODE REVIEW

**Comment by josephmcg** [comment]
Fixing bug from Mauro's feedback, translations, etc.. will change status when ready

**Review by molimauro — APPROVED** [review]

**Review by WanderingHogan — APPROVED** [review]

**Review by phillsatellite — APPROVED** [review]

**Review by stavares843 — CHANGES_REQUESTED** [review]
Captura de ecrã 2022-02-02, às 22 20 13

figma

Captura de ecrã 2022-02-02, às 22 20 26

branch

- should say add file
- corners are rounder on design
- icon inside button is not the same as design


I saw your description PR regarding the icons, but was this confirmed with design if we want to use those or not?

**Review by stavares843 — CHANGES_REQUESTED** [review]
Captura de ecrã 2022-02-02, às 22 22 31

branch

Captura de ecrã 2022-02-02, às 22 22 48

figma

- not the same icon as design

**Review by stavares843 — CHANGES_REQUESTED** [review]
Captura de ecrã 2022-02-02, às 22 25 38

when clicking on the field, has a grey bar on the left side of the icon

**Review by stavares843 — CHANGES_REQUESTED** [review]
Captura de ecrã 2022-02-02, às 22 29 20

- the upgrade is not a box button on the design
- the sections where it says ''recent'', those boxes are smaller in height compared with design
- design has more padding between the icons and the copy where it says ''recent'' for example

**Comment by WanderingHogan** [comment]
For icons and to make things pixel perfect - should we put together an epic for after alpha? I know Joe was already talking about the problems with bulma and all the local overrides we are doing and coming up with a better strategy? @stavares843 @josephmcg ?

**Comment by stavares843** [comment]
sounds good 🎉

**Comment by WanderingHogan** [comment]
@stavares843 https://satellite-im.atlassian.net/browse/AP-670

**Review by stavares843 — APPROVED** [review]

**Pull request merged**
