### PR TITLE
feat(friends): display outgoing friend requests after send

### PR DESCRIPTION
**Pull request by josephmcg**
**What this PR does** 📖
- show list of outgoing friend requests

**Which issue(s) this PR fixes** 🔨
AP-702

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

### CODE REVIEW

**Review by molimauro — APPROVED** [review]

**Comment by stavares843** [comment]
Captura de ecrã 2022-02-07, às 16 33 38
Captura de ecrã 2022-02-07, às 16 38 35

neat 💥

**Comment by stavares843** [comment]
Captura de ecrã 2022-02-07, às 16 39 11

also, what's the order this is added? I added asdadada first, then asher, then hogan but they are not added on that order or alphabetically

**Review by stavares843 — APPROVED** [review]

**Comment by stavares843** [comment]
cancel request - [AP-703](https://satellite-im.atlassian.net/browse/AP-703)

**Comment by stavares843** [comment]
added ticket to improve the order 
[AP-713](https://satellite-im.atlassian.net/browse/AP-713)

**Pull request merged**
