### PR TITLE
refactor(timestamps): switch localized timestamps to store getter

### PR DESCRIPTION
**Pull request by josephmcg**
**What this PR does** 📖
- I created some getters that provide a localized timestamp
- I wanted something reusable since we repeated this dayjs logic many times
- placed in settings store because it should rely on user selected timezone (settings store)
- added tests

**Which issue(s) this PR fixes** 🔨
AP-1729

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

### CODE REVIEW

**Review by Jekrimo — APPROVED** [review]

**Review by WanderingHogan — APPROVED** [review]

**Comment by WanderingHogan** [comment]
@stavares843 @phillsatellite to test this you should see the timestamp in the same format across group, reply items, search items

**Comment by phillsatellite** [comment]
Thanks @WanderingHogan, when I tested I was able to replicate the same bug from https://github.com/Satellite-im/Core-PWA/pull/3475#issuecomment-1149130597 but still wasn't able to replicate on dev branch 

https://user-images.githubusercontent.com/93608357/172502289-632ac184-1fa8-40ea-9624-c41496d23a59.mov

**Comment by josephmcg** [comment]
that's a relief that it's a separate bug, rather than something I'm adding here

**Review by phillsatellite — APPROVED** [review]

**Review by stavares843 — CHANGES_REQUESTED** [review]
Captura de ecrã 2022-06-08, às 17 08 48

when you go to settings and change your timezone, updates the timestamps on the messages inside the chat but doesn't update the timestamp on the sidebar where the chats are listed

**Review by phillsatellite — APPROVED** [review]

**Comment by stavares843** [comment]
image

this chat has a different timestamp sidebar vs last message

this one is correct

image

then I couldn't reproduce the bug again

merging

**Pull request merged**
