### PR TITLE
feat(glyph): send glyph message on click

### PR DESCRIPTION
**Pull request by josephmcg**
sends glyph to active friend chat on click

**What this PR does** 📖

**Which issue(s) this PR fixes** 🔨

Fixes AP-166

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

### CODE REVIEW

**Review by stavares843 — CHANGES_REQUESTED** [review]
STR:
- send a gliphy
- send another glyph
- error appears

Captura de ecrã 2021-12-08, às 01 50 10




let me know if you can reproduce on your side

browser - Chrome, macOS

**Comment by josephmcg** [comment]
Hmm I wasn't able to reproduce. Did you send the same one again or different ones?
image

**Comment by stavares843** [comment]
I tried both, the same emoji and also a different one

checking again

do you feel is possible to add something to prevent the issue in case it's not always reproducible?

**Comment by josephmcg** [comment]
ah it has something to do with the 'most used' area. I was only selecting in the main part below. Thanks Sara!

**Comment by josephmcg** [comment]
@stavares843 Fixed! I realized the top row is for filtering glyph packs, not selecting a specific one.

**Review by RetroPronghorn — APPROVED** [review]

**Comment by stavares843** [comment]
still getting the error


the branch is updated, I also restarted the server locally

Captura de ecrã 2021-12-08, às 14 58 19

Captura de ecrã 2021-12-08, às 14 57 33

**Comment by stavares843** [comment]
let me know if you need any more info and if you are able to reproduce it @josephmcg

**Review by WanderingHogan — APPROVED** [review]

**Comment by stavares843** [comment]
waiting for the fix above

**Comment by josephmcg** [comment]
will try to reproduce now, lemme know what steps you took though

**Comment by stavares843** [comment]
same steps as the video above 💥

**Comment by stavares843** [comment]
https://user-images.githubusercontent.com/29093946/145314536-719cee04-3d0f-4e7c-90ce-4d54ddf1217a.mp4

new video

**Comment by josephmcg** [comment]
was able to reproduce on dev, will look around for improper mutations. I think it's the hover state

**Comment by stavares843** [comment]
thanks for checking! 🎉

**Comment by josephmcg** [comment]
@stavares843 
I think I got it this time, please check

**Comment by stavares843** [comment]
thanks! 🎉 will check

**Comment by stavares843** [comment]
that crash is fixed ✅ 

but seems this is introducing a crash that doesn't happen on dev

https://user-images.githubusercontent.com/29093946/145338096-ebe60255-9598-43c7-ae65-a02f329f231a.mp4


The first one is this branch, the second one is dev.satellite.one

**Comment by josephmcg** [comment]
thank you 🙏 
This was introduced by something I added to fix the lazy loading after filter. Will check it out

**Comment by josephmcg** [comment]
ok please try again, thanks for your patience on this one

**Comment by josephmcg** [comment]
Actually I'm gonna refactor this a bit.. The add to chat shouldn't be the default functionality of these Icons

**Comment by josephmcg** [comment]
ok, ready. I changed this because I realized clicking a Glyph in the Marketplace modal would add to chat. GlyphItem will be much more reusable now

**Comment by stavares843** [comment]
thanks! 🎉 checking

**Comment by stavares843** [comment]
crash is fixed ✅ 

but it's not sending out glyph from the recent section

Captura de ecrã 2021-12-09, às 15 16 46


https://user-images.githubusercontent.com/29093946/145423089-e27748cf-d89d-40af-8586-37716a82df89.mp4

video above

Chrome, macOS

**Comment by josephmcg** [comment]
Yes, that's intended functionality. You will notice that the glyph selections below are filtered by the recent area

**Review by WanderingHogan — APPROVED** [review]

**Review by stavares843 — APPROVED** [review]

**Pull request merged**
