### PR TITLE
feat(solana): error popup shows whenever an error occurs to prevent infinite loading

### PR DESCRIPTION
**Pull request by vimercati-samir**
What this PR does 📖
Error popup shows whenever an error occurs to prevent infinite loading.

Which issue(s) this PR fixes 🔨

AP-1494

Special notes for reviewers 🗒️

Additional comments 🎤
The error popup looks like this and it should appear when solana is down (instead of "Aligning satellites..." infinitely): https://cdn.discordapp.com/attachments/909842607159537725/970763603324043324/Screen_Shot_2022-05-02_at_2.07.40_PM.png

### CODE REVIEW

**Comment by molimauro** [comment]
@vimercati-samir are u still working on this one or can i put the missing review label?

**Comment by vimercati-samir** [comment]
> @vimercati-samir are u still working on this one or can i put the missing review label?

working on it (I'm making changes to catch textile errors also), I'm gonna close it today

**Review by molimauro — APPROVED** [review]

**Comment by molimauro** [comment]
Code looks good! Just wondering if we should be more specific regarding the error

**Comment by molimauro** [comment]
Let's put this is ;) thanks guys

**Review by stavares843 — COMMENTED** [review]
https://user-images.githubusercontent.com/29093946/168101504-ede7f6cf-aad0-43b3-9eea-566dcc221573.mov

also noticed if you try again the loading appears above the modal and overlaps the content

**Comment by stavares843** [comment]
i'm fine with merging this and addressing these issue mentioned above later

**Review by stavares843 — COMMENTED** [review]
https://user-images.githubusercontent.com/29093946/168132525-3b3f0053-2407-4c95-ba10-40d60c391692.mov

i can only reproduce this on this branch and is a very specific issue but I wanted to ask is there anything on this PR code-wise that could create the empty view you see at 0:55s on the video above? cc @molimauro

**Comment by molimauro** [comment]
@vimercati-samir you can fix the minors on this one before merging. Let's throttle the Try Again button in order to fix the refresh spam

**Comment by molimauro** [comment]
> Gravacao.do.ecra.2022-05-12.as.18.15.36.mov 
> i can only reproduce this on this branch and is a very specific issue but I wanted to ask is there anything on this PR code-wise that could create the empty view you see at 0:55s on the video above? cc @molimauro

Doesn't seem so, i'll talk with Samir to understand what we can do, thanks!

**Comment by vimercati-samir** [comment]
All issues should be resolved in commit 4e34e65225e5408cccffd3b0c38e2b7e9517391f

**Comment by phillsatellite** [comment]
When I tested again and clicked Try Again on Modal it would just flash the Linking Satellites real quick. If i rapid clicked try again it would take me to the Linking Satellites page and stay there forever with no error 

https://user-images.githubusercontent.com/93608357/168675315-25c562c9-89c3-46c8-a8e2-60aa553acce5.mov

**Comment by vimercati-samir** [comment]
> When I tested again and clicked Try Again on Modal it would just flash the Linking Satellites real quick. If i clicked try again twice it would take me to the Linking Satellites page and stay there forever with no error
> 
>  refresh.mov

should be resolved in commit 58150cef24d36110c4030599993fe5f669facd3d

**Review by molimauro — APPROVED** [review]

**Review by phillsatellite — APPROVED** [review]

**Review by stavares843 — APPROVED** [review]

**Pull request merged**
