### PR TITLE
chore(seedPage): added copy button to seed page

### PR DESCRIPTION
**Pull request by WanderingHogan**
**What this PR does** 📖
Adds copy button to the seed page

**Which issue(s) this PR fixes** 🔨
n/a

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

### CODE REVIEW

**Review by phillsatellite — APPROVED** [review]

**Review by josephmcg — COMMENTED** [review]
could we make it a button so it's keyboard accessible?

**Comment by WanderingHogan** [comment]
@josephmcg How do you think the buttons should look?

Stacked/full width? 2 half width buttons?

**Comment by WanderingHogan** [comment]
Screen Shot 2022-06-09 at 8 51 21 PM

**Review by josephmcg — APPROVED** [review]

**Comment by stavares843** [comment]
🎉

**Review by stavares843 — APPROVED** [review]

**Pull request merged**
