### PR TITLE
fix(footer): fix online indicator for special characters

### PR DESCRIPTION
**Pull request by WanderingHogan**
**What this PR does** 📖
Fixes issues with footer related to special characters that don't work with i18n pluralization in the locales files. https://vue-i18n.intlify.dev/guide/essentials/syntax.html#special-characters
This encodes and decodes the strings we build to show the indicator.

**Which issue(s) this PR fixes** 🔨
[AP-1861](https://satellite-im.atlassian.net/browse/AP-1861) and [AP-1858](https://satellite-im.atlassian.net/browse/AP-1861)

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

### CODE REVIEW

**Review by josephmcg — APPROVED** [review]

**Comment by stavares843** [comment]
@phillsatellite  and I were testing and 


when adding a bunch of bars like this

image


and when adding that user to a group, appears like this

image


only green dot, no name

**Comment by stavares843** [comment]
when we add 2 bars like this

image


and add that user to a group appears like this

https://user-images.githubusercontent.com/93608357/174442785-f6991c09-c5fd-470e-b2bb-07322328c411.mov

**Comment by stavares843** [comment]
when adding 2 bars

https://user-images.githubusercontent.com/93608357/174442785-f6991c09-c5fd-470e-b2bb-07322328c411.mov


and adding that user to the group appears like this

https://user-images.githubusercontent.com/93608357/174442785-f6991c09-c5fd-470e-b2bb-07322328c411.mov

**Comment by molimauro** [comment]
is this ready to be reviewed? :)

**Comment by josephmcg** [comment]
@molimauro I was testing it earlier and it looked good to me, clever way to get around the restricted characters

**Review by josephmcg — APPROVED** [review]

**Comment by molimauro** [comment]
yes it is, great then!

**Comment by stavares843** [comment]
there are still changes that needs to be addressed, as discussed on discord

**Pull request closed without merging**
