### PR TITLE
feat(images): enable multiple upload, add spinner, allow multi file types

### PR DESCRIPTION
**Pull request by Jekrimo**
**What this PR does** 📖
Enables multiple uploads within chatbar. Enables file types other than images to be sent. Cleans up literal strings. Adds loading spinner to cursor. 

**Which issue(s) this PR fixes** 🔨
AP-274 / AP-275

**Special notes for reviewers** 🗒️
This is a portion of the epic for AP-231.

**Additional comments** 🎤
There is an issue when trying to send image types within TextileManager.mailboxManager.sendMessage<'image'>. Something is stopping the typing to go through even though it's matching the <'file'> typing for sendMessage exactly. I have added a investigate ticket to the epic for this issue as I have a sneaking suspicion it is textiles buckets involved.

### CODE REVIEW

**Comment by stavares843** [comment]
pretty neat! 🎨

**Review by stavares843 — CHANGES_REQUESTED** [review]
https://user-images.githubusercontent.com/29093946/146812600-6552fa4d-1ce9-4735-9023-3eed883cc9f3.mp4

i sent the 3 images but only sent 1 and the upload modal is still there

**Comment by Jekrimo** [comment]
> Screen.Recording.2021-12-20.at.6.04.08.PM.mp4 
> i sent the 3 images but only sent 1 and the upload modal is still there

Does this happen every time with three images? I'm trying to reproduce and can't get it to trigger

**Comment by Jekrimo** [comment]
> > Screen.Recording.2021-12-20.at.6.04.08.PM.mp4
> > i sent the 3 images but only sent 1 and the upload modal is still there
> 
> Does this happen every time with three images? I'm trying to reproduce and can't get it to trigger

Are you on Windows? I think I got it to trigger on my pc

**Comment by stavares843** [comment]
Chrome, macOS

**Comment by Jekrimo** [comment]
> Chrome, macOS

Thank you! I'm investigatering

**Comment by stavares843** [comment]
https://user-images.githubusercontent.com/29093946/146826589-3cb4271c-9467-40e0-806a-a578d2e3e5a5.MOV

should the cursor be more fluid/faster?

im sorry for the video quality 😂 but whenever i record my screen the cursor appears like this

https://user-images.githubusercontent.com/29093946/146826635-c1cd419e-a2bd-4958-859f-6680e76ffc5f.mp4



so i had to record with my phone 😂

**Comment by Jekrimo** [comment]
> IMG_0402.MOV 
> should the cursor be more fluid/faster?
> 
> im sorry for the video quality 😂 but whenever i record my screen the cursor appears like this
> 
>  Screen.Recording.2021-12-20.at.6.04.08.PM.mp4 
> so i had to record with my phone 😂

Yeah, I'm curious what the actual loading icon is connected too in the network, seems to rely on the progress of the load and how that is going, maybe another ticket for it

**Comment by stavares843** [comment]
sounds good, thanks 🎉 

do we have a list of all the allowed files btw?

**Comment by Jekrimo** [comment]
> 

We do not. I've  dug through textiles docs and can't find any specifics, as far as I can tell the "buckets" we upload except anything as long as it's in the correct format, but surely there have to be limitation I'm not aware of yet

**Comment by stavares843** [comment]
k thanks 🎉 

so far i tried .png, .jpeg, .jpg, .tiff, .zip, .dmg, .mov, .ogg, .js, .doc, .docx, .pdf


Captura de ecrã 2021-12-20, às 20 47 53

is possible to fix the broken thumb or add a placeholder? let me know if you need a file to reproduce

**Comment by stavares843** [comment]
Captura de ecrã 2021-12-20, às 20 49 28

copy pasted 3 images, and the cancel/send button are behind the other options on the chat bar

Chrome, macOS

**Comment by stavares843** [comment]
should the multi file picker be available when user select an item on the file picker here?

Captura de ecrã 2021-12-20, às 20 50 15

you can only select 1 if you go to chat > upload > file picker

**Comment by stavares843** [comment]
the broken thumb and the glitch are both fixed, thanks! 🎉 

Captura de ecrã 2021-12-20, às 20 52 41

**Comment by stavares843** [comment]
the max files is 4 
Captura de ecrã 2021-12-20, às 20 54 42


but on the file picker - chat bar > upload > file picker you can select more than 4

Captura de ecrã 2021-12-20, às 20 54 28

**Comment by Jekrimo** [comment]
> Captura de ecrã 2021-12-20, às 20 49 28
> 
> copy pasted 3 images, and the cancel/send button are behind the other options on the chat bar
> 
> Chrome, macOS

This should work, Can you command/ctrl click for multiple selections?

**Comment by Jekrimo** [comment]
> the max files is 4
> 
> Captura de ecrã 2021-12-20, às 20 54 42
> 
> but on the file picker - chat bar > upload > file picker you can select more than 4
> 
> Captura de ecrã 2021-12-20, às 20 54 28

Are they getting lost behind the streaming thing?

**Comment by stavares843** [comment]
> > Captura de ecrã 2021-12-20, às 20 49 28
> > copy pasted 3 images, and the cancel/send button are behind the other options on the chat bar
> > Chrome, macOS
> 
> This should work, Can you command/ctrl click for multiple selections?



this one is fixed now 🎉 

Captura de ecrã 2021-12-20, às 20 54 42

**Review by stavares843 — APPROVED** [review]

**Review by RetroPronghorn — APPROVED** [review]

**Pull request merged**
