### PR TITLE
feat(searchIndex): implement barebones solr search index

### PR DESCRIPTION
**Pull request by aewing**
**What this PR does** 📖
Introduces a simple search index using Lunr for chat search.

**Which issue(s) this PR fixes** 🔨
[AP-973](https://satellite-im.atlassian.net/browse/AP-973)

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

### CODE REVIEW

**Review by WanderingHogan — APPROVED** [review]

**Comment by phillsatellite** [comment]
Tested: Found crash on here that I wasn't able to replicate on dev branch. Select a search suggestion and press enter will crash. Error is "unrecognised field 'from', possible fields: 'payload' "

dev branch 

https://user-images.githubusercontent.com/93608357/156462639-5f104f99-13f9-41a9-bd94-5c95a6b43bdd.mov

this branch 

https://user-images.githubusercontent.com/93608357/156462661-48584488-30e1-4378-94f1-378e6a1ea24b.mov

**Comment by stavares843** [comment]
cc @aewing let us know if you were able to reproduce Phil's crash above

**Comment by aewing** [comment]
> cc @aewing let us know if you were able to reproduce Phil's crash above

I was able to reproduce this crash. I have some other changes I am working on for search and I will follow up soon.

**Comment by aewing** [comment]
Closing in favor of #1817

**Pull request closed without merging**
