### PR TITLE
fix(sign-in): reworked sign in ui, fixed "import from phrase" ui

### PR DESCRIPTION
**Pull request by ThomBos**
**What this PR does** 📖
Fixes ui on register and log in pages where broken, small rework of sign in page. 
These changes should improve also graphics on mobile devices.
**Which issue(s) this PR fixes** 🔨
AP-2202

**Special notes for reviewers** 🗒️
Let me know if the logo on the sign in page looks good, otherwise i can remove it
**Additional comments** 🎤

### CODE REVIEW

**Comment by ThomBos** [comment]
@josephmcg i've seen those "padding: 16px 24px" already on the previous styling, so i proceeded using them instead of spacing variables... Are we going to remove the rems variables or should i convert these changes i've done?

**Comment by aewing** [comment]
Please don't merge this. It will have major conflicts with the work I have in progress.

**Comment by stavares843** [comment]
update snap to fix Jest tests 🔨

**Comment by stavares843** [comment]
original content before i fixed the snap

https://github.com/Satellite-im/Core-PWA/pull/4519/commits/658b22d8a862b2aa314727c5b56c2930bb5fd59e

**Comment by josephmcg** [comment]
Definitely want to get rid of the variables at some point. It's very situational whether a person should use rem/px/em. Most of the time, px are good. In cases of vertically spacing text (whether its gap, margin, or padding), I could see rem being viable as well

**Comment by iltumio** [comment]
> 

do you mean that the fix is not needed anymore after the onboarding rework? or it has to be applied after your PR?

**Comment by iltumio** [comment]
> Please don't merge this. It will have major conflicts with the work I have in progress.

do you mean that the fix is not needed anymore after the onboarding rework? or it has to be applied after your PR?

**Comment by ThomBos** [comment]
> Definitely want to get rid of the variables at some point. It's very situational whether a person should use rem/px/em. Most of the time, px are good. In cases of vertically spacing text (whether its gap, margin, or padding), I could see rem being viable as well
> 
> Try to think.. Do I want this value scaling with the user selected font size?

that's exactly what i thought, thanks 🔨

**Comment by aewing** [comment]
> > Please don't merge this. It will have major conflicts with the work I have in progress.
> 
> do you mean that the fix is not needed anymore after the onboarding rework? or it has to be applied after your PR?

I have some pretty major changes to the authentication/lock/import/export functionality and use different routes for those changes. Ultimately this is just a request, since my wallet work is sidelined until we get the major blockers addressed, but I am still hopeful I can get it into a PR shortly after we cut a stable build.

**Comment by WanderingHogan** [comment]
@ThomBos closing this, but leaving the branch open, as the updates Drew made to the Nicholas' wallet PR will change a lot of this flow. We are going to keep the branch to try and cherry pick things once sync/performance things aren't the pirmary focus

**Pull request closed without merging**
