### PR TITLE
fix(sidebar-list-item): time section constraining last message width

### LINKED ISSUE #4753: time constraining last message in sidebar list item
スクリーンショット 2022-09-13 午後6 40 51

### PR DESCRIPTION
**Pull request by nathan-power**
### What this PR does 📖
Before:
スクリーンショット 2022-09-13 午後6 40 51

After:
スクリーンショット 2022-09-13 午後7 07 21

### Which issue(s) this PR fixes 🔨
- Resolve #4753

### CODE REVIEW

**Comment by stavares843** [comment]
strange on dev earlier was already like this

image

**Comment by stavares843** [comment]
Captura de ecrã 2022-09-14, às 02 20 56


Captura de ecrã 2022-09-14, às 02 21 29


SHADY

as long is fixed 😂

**Comment by stavares843** [comment]
or only happens if you have the yesterday timestamp?

**Comment by nathan-power** [comment]
https://app.usebubbles.com/pVZvZ4qkUEFzPMV88jyV1J/my-video-recording

Kind of. The timestamps in dev currently have div containers that are also taking up the space below them, so if the timestamp is short then it still looks natural, but for wide timestamps the last message text gets pushed to the side

**Comment by stavares843** [comment]
💣

**Review by josephmcg — APPROVED** [review]

**Pull request merged**
