### PR TITLE
refactor(friendsmanager): different error handling aproach

### PR DESCRIPTION
**Pull request by ThomBos**
**What this PR does** 📖
Improves error handling in the friendsmanager 
**Which issue(s) this PR fixes** 🔨

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

### CODE REVIEW

**Comment by ThomBos** [comment]
i was wondering if changing the error's display from text to a popup (like the "toast" component but red), was a good idea or not.... changing this here would mean change errors display all around the app. 
was thinking about this because errors, like lost connection, can occur while the user is on any page and he doesn't have any feedback whenever this happens

**Review by josephmcg — CHANGES_REQUESTED** [review]
i don't understand the design decision of throwing an error and catching it inside the same method. Throwing errors are helpful if you intend to bubble it up and catch it elsewhere.

An example of the above technique can be found in this method `validateName` (https://github.com/Satellite-im/Core-PWA/blob/iridium-dev/libraries/Iridium/files/FilesManager.ts#:~:text=*/-,private,-validateName(name). It will throw an error which is then caught all the way back in `components/views/files/controls/Controls.vue` `addFolder` and `handleFile`

instead of try/catch in the same method, you may as well just manually set error to whatever value, then return.

*more importantly - With regards to the overall structure. Could you explain your thought process?

My thoughts are that an error pertains to a single friends operation (add, send request, accept, etc), so you don't need to keep the error stored in iridium. You should be able to throw it, and then let the component handle it

**Comment by ThomBos** [comment]
I'd have gone the way you said if the components which display the error were made in a different way... I've tried as well returning error strings instead of throwing them, but the "issue" is still the same.
Right now we have a child component which calls friendsmanager's functions (it would be the place where to catch the errors) and the parent component that reads the errors computed property, then displays it.
I went for this solution mainly to avoid emitting all the stuff from the child component...

So actually i have no idea how to handle it avoiding errors emits in the child component (or friendmanager) and get the same try catch process you suggested

**Comment by josephmcg** [comment]
gotcha, I can take a look on monday to see if there's a simpler approach. If it can't wait until then, maybe Mauro would be able to guide you in the right direction

**Comment by josephmcg** [comment]
since Thomas is out of office, I didn't check this today. will fix sometime this week. I was more focused on adding new functionality in chat

**Comment by ThomBos** [comment]
> since Thomas is out of office, I didn't check this today. will fix sometime this week. I was more focused on adding new functionality in chat
> 
> -- edit because the friends connection stuff is a bit wonky, decided it was better to wait

Since lot as changed with Muhammad's work, is this Pr still useful or it can be deleted?

**Pull request closed without merging**
