### PR TITLE
feat(iOS): iOS Cleanup & LESS rewrite

### PR DESCRIPTION
**Pull request by RetroPronghorn**
**What this PR does** 📖
This PR cleans up a ton of less code as well as fixes a bunch of visual bugs with the iOS PWA.

### CODE REVIEW

**Comment by stavares843** [comment]
checking 🔨

**Comment by stavares843** [comment]
click on any of these
Captura de ecrã 2021-12-19, às 02 39 49

returns error
Captura de ecrã 2021-12-19, às 02 38 26

I compiled dev branch as well locally and was fine

I run yarn as well to be sure everything was set up properly

**Comment by stavares843** [comment]
selecting an option on the marketplace appears like this

Captura de ecrã 2021-12-19, às 02 45 57

vs dev

Captura de ecrã 2021-12-19, às 02 46 51

**Comment by stavares843** [comment]
colors are missing when going to wallet

Captura de ecrã 2021-12-19, às 02 52 26

vs dev

Captura de ecrã 2021-12-19, às 02 52 33

**Comment by stavares843** [comment]
missing colors on settings > realms

is missing the red/green copy where it says true/false

Captura de ecrã 2021-12-19, às 02 55 42

vs dev

Captura de ecrã 2021-12-19, às 02 55 47

**Comment by stavares843** [comment]
going to files shows the bar green instead of blue, not sure if is a change in purpose

Captura de ecrã 2021-12-19, às 02 57 36

vs dev

Captura de ecrã 2021-12-19, às 02 57 40

**Review by stavares843 — CHANGES_REQUESTED** [review]
added a couple comments 🔨

**Comment by RetroPronghorn** [comment]
> selecting an option on the marketplace appears like this
> 
> Captura de ecrã 2021-12-19, às 02 45 57
> 
> vs dev
> 
> Captura de ecrã 2021-12-19, às 02 46 51
> 
> Chrome, macOS

I'm going to redo this sidebar anyways, let's not worry about this one. It doesn't fit the sidebar style of the rest of our app.

**Comment by RetroPronghorn** [comment]
I think I've fixed the rest. please ignore the center align issues on the mobile signup. I did this intentionally so that your thumbs have to reach less far to use the app.

**Review by WanderingHogan — APPROVED** [review]
comments dm'ed

**Comment by stavares843** [comment]
create a server 

this branch
Captura de ecrã 2021-12-19, às 22 48 37


vs dev

Captura de ecrã 2021-12-19, às 22 48 26

iPhone 6/7/8 Plus

**Comment by stavares843** [comment]
going to chat > glyphs/emojis

Captura de ecrã 2021-12-19, às 22 52 42

vs dev

Captura de ecrã 2021-12-19, às 22 52 48

iPhone 6/7/8 Plus

**Review by stavares843 — CHANGES_REQUESTED** [review]
pretty neat! 🎉

**Review by stavares843 — APPROVED** [review]

**Pull request merged**
