### PR TITLE
fix(sidebar): change styles for friends request label

### PR DESCRIPTION
**Pull request by AlexZakablukov**
**What this PR does** 📖
change styles for friends request label

**Which issue(s) this PR fixes** 🔨
[AP-1455](https://satellite-im.atlassian.net/browse/AP-1455)

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

### CODE REVIEW

**Review by Jekrimo — APPROVED** [review]

**Comment by phillsatellite** [comment]
Tested: Seems like notification on Safari is still a little thinner than the notification on Chrome. 

Chrome left - Safari right
Screen Shot 2022-04-26 at 1 57 53 PM

**Review by phillsatellite — APPROVED** [review]

**Comment by AlexZakablukov** [comment]
> Captura de ecrã 2022-04-28, às 14 59 37
> 
> seems this is adding bold on more copy
> 
> this branch vs dev, the ''helios'' is bolder

Hello, I connected the correct fonts to the project before they were not for bold

**Comment by Clayton215** [comment]
friends icon

Looks good

**Review by Clayton215 — APPROVED** [review]

**Comment by AlexZakablukov** [comment]
So should I change something in this pr?

**Review by molimauro — APPROVED** [review]

**Review by phillsatellite — APPROVED** [review]

**Review by stavares843 — APPROVED** [review]

**Pull request merged**
