### PR TITLE
feat(settings): settings header component

### LINKED ISSUE #4919: add nav back to mobile settings pages

### PR DESCRIPTION
**Pull request by jasonwoodland**
### What this PR does 📖
- Add SettingsHeader component
- Fix mobile styling on settings page
- Add settings page header

### Which issue(s) this PR fixes 🔨
- Resolve #4919

### CODE REVIEW

**Comment by molimauro** [comment]
Looks good, only one minor thing: If i go to Settings > Personalize and then click the back arrow on top i get this:

image

**Comment by jasonwoodland** [comment]
@molimauro Thanks! did any of the other pages do it? I'll add a null check now

**Comment by jasonwoodland** [comment]
I would have liked to use the `useSwiper` hook, but we're using the old version of swiper, so I had to use the `$el.closest()` method

**Comment by molimauro** [comment]
> @molimauro Thanks! did any of the other pages do it? I'll add a null check now

Yes pretty much every page seems to be affected

**Comment by jasonwoodland** [comment]
Chrome?

**Comment by molimauro** [comment]
Yes!

**Comment by molimauro** [comment]
> I would have liked to use the `useSwiper` hook, but we're using the old version of swiper, so I had to use the `$el.closest()` method

cant we update that? :)

**Comment by jasonwoodland** [comment]
we definitely should, just didn't want to exceed the scope of this pr

**Comment by jasonwoodland** [comment]
I can't reproduce the problem you're having, I'm getting @nathan-power to test also

**Comment by molimauro** [comment]
Yes i totally agree! Let's open a ticket then :)

**Comment by jasonwoodland** [comment]
Opened https://github.com/Satellite-im/Core-PWA/issues/4921

**Comment by molimauro** [comment]
> I can't reproduce the problem you're having, I'm getting @nathan-power to test also

Maybe this can help!

https://user-images.githubusercontent.com/50131258/190969321-85f4b0db-6180-4ac4-a902-ea9ae0ec597b.mov

**Comment by jasonwoodland** [comment]
@molimauro Could you please try that I just pushed, I'm not sure why else it won't be able to find the swiper ancestor in the dom tree.

**Comment by nathan-power** [comment]
Just an update, it seems it's working on my end

**Comment by molimauro** [comment]
Yes it's working now! I noticed that before was working locally but not on fleek preview 🤔 Seems fixed now though, thanks!

**Comment by jasonwoodland** [comment]
Nice, thanks for checking it out :)

**Review by molimauro — APPROVED** [review]

**Pull request merged**
