### PR TITLE
fix(chat): Implement input length limit for quick profile

### PR DESCRIPTION
**Pull request by genie-magic**
**What this PR does** 📖
-move max chars to config for several components
-Implement input length limit for quick profile
**Which issue(s) this PR fixes** 🔨

AP-295

### CODE REVIEW

**Review by stavares843 — CHANGES_REQUESTED** [review]
emoji gets counted as 2
Captura de ecrã 2021-12-20, às 16 41 06

instead of 1

Captura de ecrã 2021-12-20, às 16 41 22

**Review by RetroPronghorn — APPROVED** [review]

**Comment by genie-magic** [comment]
> emoji gets counted as 2 Captura de ecrã 2021-12-20, às 16 41 06
> 
> instead of 1
> 
> Captura de ecrã 2021-12-20, às 16 41 22

@stavares843  I fixed this issue and pushed.

**Comment by RetroPronghorn** [comment]
Please rebase

**Comment by genie-magic** [comment]
@RetroPronghorn  @WanderingHogan  I am very sorry about it being merged.
After I git rebase dev... I git pull and that was my mistake. that occurred conflict.
From this time, I will keep this in mind.

**Pull request closed without merging**
