### PR TITLE
fix(chat): send message after store&publish

### PR DESCRIPTION
**Pull request by molimauro**
### What this PR does 📖
- Make sure not to append the message in chat until it has been stored and published in iridium. The loader in chat is missing though

### Which issue(s) this PR fixes 🔨
- Resolve #

### CODE REVIEW

**Review by WanderingHogan — APPROVED** [review]

**Comment by WanderingHogan** [comment]
good idea

**Comment by stavares843** [comment]
not saying this is from the PR just to be informative (even though prod has/had a similar bug)

this PR

- phil added me to a group with 4 users

image

- on my side was only 2 users and no messages

image


we did the same on core and i was able to get the messages from the other users + they were on the group list as well


note
- before on prod there was this [bug](https://github.com/Satellite-im/Core-PWA/issues/4852) similar, not the same even though i can no longer reproduce that atm

**Comment by WanderingHogan** [comment]
i've seen that other bug on prod before and think it's unrelated, this should take care of the issue where you can send things and see it on one side, reload, and then not see it on the other because iridium didn't receive it yet

**Comment by stavares843** [comment]
fine by me i also saw a similar one on prod that i added above but adding this just for info 😂

**Pull request merged**
