### PR TITLE
Chatbar should always be visible - AP-151 

### PR DESCRIPTION
**Pull request by davidchan1219**
**What this PR does** 📖

**Which issue(s) this PR fixes** 🔨

AP-151

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

### CODE REVIEW

**Review by stavares843 — CHANGES_REQUESTED** [review]
I'm on the correct branch, is updated, I even redeployed a new server locally but the chat bar is not appearing on this chat below

Captura de ecrã 2021-12-08, às 16 15 25


the ticket [AP-151](https://satellite-im.atlassian.net/browse/AP-151) mentions the following

Captura de ecrã 2021-12-08, às 16 16 50



Captura de ecrã 2021-12-08, às 16 15 49

**Comment by davidchan1219** [comment]
@stavares843 can you test it on AP151 branch after refresh browser?

**Comment by stavares843** [comment]
yes I did that

is the chat bar appearing on your side on the Phoenix chat?

**Comment by davidchan1219** [comment]
@stavares843 please test it again after pull. thanks

**Comment by stavares843** [comment]
i did

**Review by WanderingHogan — APPROVED** [review]

**Review by stavares843 — APPROVED** [review]

**Pull request merged**
