### PR TITLE
fix(files): nsfw scan memory limit

### PR DESCRIPTION
**Pull request by josephmcg**
**What this PR does** 📖
- prevent crash by placing a memory limit on scan
- rename our nsfw limits accordingly
- remove guard clause for what I thought was a buffer issue. It was from video scan
- progress bar on upload and download
- status messages during upload indicating which file / index update
- fix unrelated display issue where mobile hamburger menu is present in desktop view
- fix css issue for fullscreen file view icons, `close` popup was cutoff. Improve overall layout using padding so progress bar wont touch the sides on mobile

**Which issue(s) this PR fixes** 🔨
AP-1280, AP-918

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

### CODE REVIEW

**Review by WanderingHogan — APPROVED** [review]

**Comment by phillsatellite** [comment]
Tested: Should an error message or something similar appear when trying to upload? I used same file Sara used for the crash and so far no crash has just been loading for about 10 mins now 
Screen Shot 2022-03-31 at 5 06 14 PM

**Comment by josephmcg** [comment]
would be helpful to check your network tab to see if it's pushing the file to textile. How much ram do you have?

**Comment by phillsatellite** [comment]
@josephmcg Hello! Not sure if this screenshot helps or not, I also have 16GB Ram and internet is 264.6Mbps 
Screen Shot 2022-04-04 at 10 46 31 AM

**Comment by josephmcg** [comment]
@phillsatellite I added a progress meter on uploads so this should be easier to test now

**Comment by stavares843** [comment]
Captura de ecrã 2022-04-07, às 15 44 13

trying to upload the 2GB file into files, returns the above error

same file used on previous testing and also by phil

**Comment by josephmcg** [comment]
Thanks, I'm trying some things out.. Can't fully test without these two bug fixes first
https://github.com/Satellite-im/Core-PWA/pull/2745
https://github.com/Satellite-im/Core-PWA/pull/2783

**Comment by stavares843** [comment]
https://github.com/Satellite-im/Core-PWA/pull/2745 - added comment 🔨 
https://github.com/Satellite-im/Core-PWA/pull/2783 - merged 🎉

**Comment by stavares843** [comment]
https://github.com/Satellite-im/Core-PWA/pull/2745 - merged 🎉

**Comment by phillsatellite** [comment]
For the memory limit, is there supposed to be an error message that appears? Uploading a 2GB File with no crash so far but also no error message about size 
Screen Shot 2022-04-12 at 1 53 19 PM

**Review by WanderingHogan — APPROVED** [review]

**Comment by stavares843** [comment]
Captura de ecrã 2022-04-12, às 23 32 46

the progress bar is pretty neat but disappears if you go to chat and then back to files for example

maybe we can improve that on other PR

besides that, pretty neat 🎉

**Review by stavares843 — APPROVED** [review]

**Comment by stavares843** [comment]
[AP-1395](https://satellite-im.atlassian.net/browse/AP-1395)

**Pull request merged**
