### PR TITLE
feat(Alerts): added alerts

### PR DESCRIPTION
**Pull request by RetroPronghorn**
**What this PR does** 📖
Adds an alerts library as well as a component to display them (`components/views/navigation/toolbar/alerts`) . It also refactors a LOT of the application so please test thoroughly.

image

also adds

https://user-images.githubusercontent.com/1770198/145965793-490bc457-b3dc-40f0-a7ba-34e39dd0ef39.mov

### CODE REVIEW

**Review by josephmcg — APPROVED** [review]
LGTM

**Review by Jekrimo — APPROVED** [review]

**Review by WanderingHogan — CHANGES_REQUESTED** [review]
I just want to pause this for a few more hours

**Review by stavares843 — CHANGES_REQUESTED** [review]
Going to the solana fake chat appears the below error on the console, the same doesn't happen on dev

Captura de ecrã 2021-12-14, às 23 46 33

Captura de ecrã 2021-12-14, às 23 46 25

flow
- go to this branch
- go to solana fake chat


besides the error, the lateral menu is gone as well

**Review by stavares843 — CHANGES_REQUESTED** [review]
On this branch, I can't make a new account from scratch, gets stuck on this view

no relevant errors on the log

Captura de ecrã 2021-12-14, às 23 39 35

import works fine

flow
- yarn dev to a new localhost or go to a new browser or a private browser
- do all the create account flow
- on the end of the flow, gets stuck on the above view

i already rebooted the mac, made a new localhost server, tried a new browser, private and non private but was the same

**Review by stavares843 — CHANGES_REQUESTED** [review]
going to settings > realm > returns the below error on console

Captura de ecrã 2021-12-14, às 23 52 00

Captura de ecrã 2021-12-14, às 23 52 15

flow
- go to localhost
- settings
- realms

**Review by stavares843 — CHANGES_REQUESTED** [review]
this adds a crash that doesn't happen on dev

flow
- go to settings
- developer
- write on the input field
- crash

https://user-images.githubusercontent.com/29093946/146097967-5fb0c98e-5e27-49eb-ab77-4bf5694fbef5.mp4

**Review by stavares843 — CHANGES_REQUESTED** [review]
going to chat > send money > returns error on console that doesn't happen on dev

Captura de ecrã 2021-12-15, às 00 01 30
Captura de ecrã 2021-12-15, às 00 01 30

**Review by stavares843 — CHANGES_REQUESTED** [review]
going to files returns error on the console, doesn't happen on dev
Captura de ecrã 2021-12-15, às 00 05 29
Captura de ecrã 2021-12-15, às 00 05 41

flow
- go to localhost
- files

**Review by stavares843 — CHANGES_REQUESTED** [review]
going to files > click on the zip file > returns error on console, doesn't happen on dev

Captura de ecrã 2021-12-15, às 00 06 57
Captura de ecrã 2021-12-15, às 00 07 06


flow
- go to localhost
- files
- go to the zip one
- error appears on console

**Review by stavares843 — CHANGES_REQUESTED** [review]
going to the status bar > marketplace
Captura de ecrã 2021-12-15, às 00 15 13

returns the below error, doesn't happen on dev
Captura de ecrã 2021-12-15, às 00 14 45
Captura de ecrã 2021-12-15, às 00 14 39

**Review by stavares843 — CHANGES_REQUESTED** [review]
seems is missing a string after dismissing all the alerts

Captura de ecrã 2021-12-15, às 00 16 55

**Comment by RetroPronghorn** [comment]
> On this branch, I can't make a new account from scratch, gets stuck on this view
> 
> no relevant errors on the log
> 
> Captura de ecrã 2021-12-14, às 23 39 35
> 
> import works fine
> 
> flow
> 
> * yarn dev to a new localhost or go to a new browser or a private browser
> * do all the create account flow
> * on the end of the flow, gets stuck on the above view
> 
> i already rebooted the mac, made a new localhost server, tried a new browser, private and non private but was the same

I think this is related to solana being down

**Comment by RetroPronghorn** [comment]
> seems is missing a string after dismissing all the alerts
> 
> Captura de ecrã 2021-12-15, às 00 16 55

Will add later

**Comment by RetroPronghorn** [comment]
> going to the status bar > wallet Captura de ecrã 2021-12-15, às 00 15 13
> 
> returns the below error, doesn't happen on dev Captura de ecrã 2021-12-15, às 00 14 45 Captura de ecrã 2021-12-15, às 00 14 39

fixed

**Comment by RetroPronghorn** [comment]
> going to files > click on the zip file > returns error on console, doesn't happen on dev
> 
> Captura de ecrã 2021-12-15, às 00 06 57
> 
> Captura de ecrã 2021-12-15, às 00 07 06
> 
> flow
> 
> * go to localhost
> * files
> * go to the zip one
> * error appears on console

Issue existed before my changes, but fixed anyways :)

**Review by WanderingHogan — APPROVED** [review]

**Review by stavares843 — APPROVED** [review]

**Comment by stavares843** [comment]
the alerts and the animation on the chat on the bottom are pretty neat! 🎉

**Pull request merged**
