### PR TITLE
feat(jest): 50% coverage for AudioStreamUtils

### PR DESCRIPTION
**Pull request by drepram**
**What this PR does** 📖

Attempt to increase coverage. Ran into an issue on line 35 at the AudioStreamUtils.ts file, 
image

Which on Jest we see as:

image

Please let me know if there ought to be improvements I make. Thank you.

**Which issue(s) this PR fixes** 🔨

AP-2246

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

### CODE REVIEW

**Review by stavares843 — APPROVED** [review]

**Comment by nathan-power** [comment]
Hey @molimauro 👋 
The deprecated AudioContext logic in question was moved from a different WebRTC related component, so you might know more than I do regarding this issue.
I briefly looked into alternatives for AudioContext such as using AudioWorklets, but it seems like it would require changing the logic quite a bit.
Do you think we should rewrite the method containing the deprecated code now, or do you think it might be better to just create an issue for the time being and focus on prioritizing current tasks?

**Comment by molimauro** [comment]
I d create a ticket and take care later of this issue, it’s low priority now ;)

**Comment by stavares843** [comment]
@molimauro what are you doing here? 😂

**Comment by molimauro** [comment]
> 

👻

**Comment by WanderingHogan** [comment]
@drepram @molimauro closing this PR for now, but leaving the branch

Added info about this to the backlog so we can come back to it after we aren't focused on EA
https://github.com/orgs/Satellite-im/projects/3/views/2

**Pull request closed without merging**
