### PR TITLE
fix(double-requests): filtered incoming requests

### PR DESCRIPTION
**Pull request by ThomBos**
**What this PR does** 📖
Fixes double requests issue
**Which issue(s) this PR fixes** 🔨

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

### CODE REVIEW

**Review by molimauro — APPROVED** [review]

**Review by stavares843 — CHANGES_REQUESTED** [review]
Screenshot 2022-06-17 at 16 25 51

still happens

**Comment by stavares843** [comment]
seems a always reproducible flow is
- user B adds user A
- go to user A tab on the browser before even get the request
- duplicated

**Review by molimauro — APPROVED** [review]

**Comment by stavares843** [comment]
image


phil added me, still duplicated

**Review by WanderingHogan — APPROVED** [review]

**Review by phillsatellite — APPROVED** [review]

**Comment by stavares843** [comment]
🎉

**Review by stavares843 — APPROVED** [review]

**Pull request merged**
