### PR TITLE
chore(chat): set read on conversation scroll bottom

### LINKED ISSUE #5466: update conversation.readAt on scroll bottom reached

### PR DESCRIPTION
**Pull request by molimauro**
### What this PR does 📖
- Title

### Which issue(s) this PR fixes 🔨
- Resolve #5466 

### Special notes for reviewers 🗒️
- 

### Additional comments 🎤
-

### CODE REVIEW

**Comment by josephmcg** [comment]
I think Jason initially designed it to only mark as read if the user scrolls to the new message indicator. something to consider, this implementation could mark all messages as unread, even if the user hasn't seen unread messages offscreen above

**Comment by molimauro** [comment]
Oh yeah i know, this is just the first piece sorry i should have mentioned. The idea is to bring the user with the scroll to the first unread message when entering the chat. As a consequence this will be natural what do you think? :)

**Comment by molimauro** [comment]
@josephmcg (can you also review this please)

**Review by josephmcg — APPROVED** [review]
Gotcha thanks for the insight, sounds good

**Review by phillsatellite — APPROVED** [review]

**Pull request merged**
