### PR TITLE
feat(signaling): ui update to soon allow user to set signaling servers

### PR DESCRIPTION
**Pull request by WanderingHogan**
What this PR does 📖
These are fixes for David's PR https://github.com/Satellite-im/Core-PWA/pull/1815. This adds in a section when signing up and in settings that allows a user to change signaling servers.

This is only a UI update, and does not have any new functionality. Changing will not change the signaling servers used yet.

Which issue(s) this PR fixes 🔨
AP-1014

Special notes for reviewers 🗒️

Additional comments 🎤

### CODE REVIEW

**Review by molimauro — APPROVED** [review]

**Review by genie-magic — APPROVED** [review]

**Comment by stavares843** [comment]
image

on sign up, there's no scroll 🔨 it breaks mobile sign up

**Comment by stavares843** [comment]
Unlock pin should be persisted when store pin is enabled -- Create Account with store pin disabled (failed)

is broken using 1000x600 screen on sign up


dev

Captura de ecrã 2022-03-22, às 22 56 34

**Comment by stavares843** [comment]
https://user-images.githubusercontent.com/29093946/159753683-0c7c6f7c-00f9-4621-b5ee-3488254ee1f9.mov

I can't scroll properly, if I try to scroll down, goes up

**Comment by phillsatellite** [comment]
In regards to Sara’s latest comment I tested on actual iOS device and it deep seem a little laggy 

Uploading IMG_4896.MOV…

**Comment by stavares843** [comment]
thanks @phillsatellite 🎉

**Review by phillsatellite — APPROVED** [review]

**Review by stavares843 — APPROVED** [review]

**Pull request merged**
