### PR TITLE
chore(action): eslint/prettier

### PR DESCRIPTION
**Pull request by stavares843**
### What this PR does 📖

Github Action with annotations if anyone tries to bypass the pre commit hook.

This will only check the modified files in the PR, not the whole codebase.

Example, in this PR, I declared 2x the same import, and returned a warning from eslint

Captura de ecrã 2022-09-28, às 23 13 06

I also grabbed a file and added extra spacing, and returned a warning from prettier

Captura de ecrã 2022-09-28, às 23 13 34

you can also use the commit button to commit the suggestion from the bot 

Captura de ecrã 2022-09-28, às 23 13 59

### CODE REVIEW

**Comment by josephmcg** [comment]
i think it's cool

**Comment by stavares843** [comment]
thanks @josephmcg 😂 1 point for bot

**Comment by molimauro** [comment]
This is great @stavares843! Is this still a draft?

**Comment by stavares843** [comment]
its ready, i just need to revert those code changes that i made to trigger the bot 😂 

and i need to know if @WanderingHogan is on board with this, im assuming not 😂

**Review by WanderingHogan — CHANGES_REQUESTED** [review]
hmm

**Comment by stavares843** [comment]
hogan said yes 😂

**Pull request merged**
