### PR TITLE
fix(chatbar-focus): fixed conflict between chatbar and searchbar focus

### PR DESCRIPTION
**Pull request by ThomBos**
**What this PR does** 📖
Fixes search input's loss of focus caused by the chatbar 
**Which issue(s) this PR fixes** 🔨
AP-1949

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

### CODE REVIEW

**Review by josephmcg — CHANGES_REQUESTED** [review]
could you help me understand the goal of this? is it specifically for mobile?

**Comment by ThomBos** [comment]
> could you help me understand the goal of this? is it specifically for mobile?

yeah it should be just for mobile but, i don't see the if that filters clickoutside tho...

**Comment by josephmcg** [comment]
> > could you help me understand the goal of this? is it specifically for mobile?
> 
> yeah it should be just for mobile but, i don't see the if that filters clickoutside tho...

thanks, you could call a method with a guard clause.
`if (this.$device.isDesktop){
return
}
blur logic here`

**Comment by WanderingHogan** [comment]
well that was a disaster

**Review by aewing — APPROVED** [review]

**Comment by aewing** [comment]
@ThomBos can we cherry-pick the valid commits from this PR onto `iridium-dev` so we can close this PR?

**Comment by stavares843** [comment]
> could you help me understand the goal of this? is it specifically for mobile?

the bug wasn't mobile only, was on desktop as well

[AP-1949](https://satellite-im.atlassian.net/browse/AP-1949)

**Comment by josephmcg** [comment]
@stavares843 I think the initial bug here was caused by a 'fix' for chatbar keeping mobile focus when it should not.
We'll build this out again if we're still having the same issue later. there have been several changes to chat, especially when it comes to mobile

**Pull request closed without merging**
