### PR TITLE
test(cypress): updates for chat commands and chat pair tests

### PR DESCRIPTION
**Pull request by luisecm**
**What this PR does** 📖
- Small improvements to cypress commands for chat features to point the scroll initially to the last item before doing any action.
- Improvement to chat pair features cypress test for timestamp assertion to validate with a regex using a chai assertion
- Skipping tests from chat-pair-features.js and chat-top-toolbar.js in the meantime we change the accounts used for this testing
- Skipping chat features tests in the meantime I got fixed the accounts affected by the db and the click/type issues on script is fixed
- Replace cy.visit('/') for visit root cypress command in tests that require this change to avoid issues caused by localstorage not removed before starting

**Which issue(s) this PR fixes** 🔨
AP-1131

**Special notes for reviewers** 🗒️
The cypress-parallel plugin was tested for this JIRA ticket but it was found that the time was increasing when using it, so no changes are being added and plugin will not be implemented

**Additional comments** 🎤
Cypress Video For Chat-Features.js

https://user-images.githubusercontent.com/35935591/159775962-559af0e2-3eba-4643-9e5a-84b67b35b1e2.mp4

### CODE REVIEW

**Review by stavares843 — APPROVED** [review]

**Review by WanderingHogan — APPROVED** [review]

**Comment by stavares843** [comment]
Chat Features Tests -- Chat - Edit message on chat (failed)
Chat Features Tests -- Chat - Send message on chat (failed)



CI

**Comment by luisecm** [comment]
Skipping chat features tests in the meantime I got fixed the accounts affected by the db and the click/type issues on script is fixed

**Comment by luisecm** [comment]
Adding one more commit to use command of visiting root page instead of cy.visit('/')

**Comment by stavares843** [comment]
thanks @luisecm 🔨

**Pull request merged**
