### PR TITLE
feat(releaseData): add new hook for release data

### PR DESCRIPTION
**Pull request by josephmcg**
### What this PR does 📖
- create new compositions folder outside of /components. All compositions should be moved here eventually. we get lots of console warning about the current structure missing default exports
- settings modal is fetching data every single mount. This will fetch one time on first render, then never again.
- not yet implemented, waiting for other refactor to go through first

### Which issue(s) this PR fixes 🔨
- Resolve #

### Special notes for reviewers 🗒️
- 

### Additional comments 🎤
-

### CODE REVIEW

**Comment by molimauro** [comment]
There is also the built-in `https://nuxtjs.org/docs/features/data-fetching`

**Comment by josephmcg** [comment]
oh cool, are there any benefits to using nuxt to fetch data?

**Comment by molimauro** [comment]
oh it provides you all the fetching utilities, options, as well as the various pending/error states, the automatic caching on page revisits, browser refresh etc. Maybe we can even use this directly: https://v3.nuxtjs.org/getting-started/data-fetching#usefetch

**Comment by josephmcg** [comment]
im ok merging for now, down to take another look later

**Pull request merged**
