### PR TITLE
fix(onlineStatus): update peer events handlers

### PR DESCRIPTION
**Pull request by pavlzk**
**What this PR does** 📖
Sometimes online status of friends and conversation participants is not updated. This PR intended to fix the issue.

**Which issue(s) this PR fixes** 🔨
AP-1697

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

### CODE REVIEW

**Comment by ThomBos** [comment]
I'd approve this because i tested it and it worked nicely, but i'd rather waiting for someone more experienced (this code looks good too me) 🙈

**Comment by phillsatellite** [comment]
A few things I found but this pr is awesome 🔥 
1. When you are adding a user, they will always appear offline when you are sending request 
Screen Shot 2022-06-10 at 2 26 09 PM

2. I wasn't able to ever get an iOS user connected when using the Netlify link
Screen Shot 2022-06-10 at 2 40 22 PM

**Comment by josephmcg** [comment]
seems like we're always mapping state as offline. maybe it was intended to protect the user's privacy?
components/views/friends/add/Add.vue

image

**Comment by molimauro** [comment]
> seems like we're always mapping state as offline. maybe it was intended to protect the user's privacy? components/views/friends/add/Add.vue
> 
> image

nope that was not intended! At that time the state wasnt working

**Comment by WanderingHogan** [comment]
Rebuilding to get the deploy preview up.

1. We can hide the online/offline indicator on the friend request or move updating that into another ticket in the EA epic

**Comment by WanderingHogan** [comment]
2. Using the fleek URL I went iphone to desktop and it connected right away. Noticed an unrelated problem we need a ticket for that i also see on the dev branch
image

**Review by WanderingHogan — APPROVED** [review]

**Comment by tooshel** [comment]
> 2. Using the fleek URL I went iphone to desktop and it connected right away. Noticed an unrelated problem we need a ticket for that i also see on the dev branch
 . . . . ticket is here: https://satellite-im.atlassian.net/browse/AP-1821

**Review by stavares843 — CHANGES_REQUESTED** [review]
2 things

still getting the not connected bug

Screenshot 2022-06-16 at 15 38 21

i made 2 accounts, added as friend both were connected but on one of them shows as not connected

also, when creating new account this section here

Screenshot 2022-06-16 at 15 37 32

takes a bunch of time to show as

Screenshot 2022-06-16 at 15 37 38


this doesn't happen on dev

**Comment by stavares843** [comment]
even though is not fully fixed works after refreshing


iOS doesn't seem it connects at all as mentioned by @phillsatellite

**Review by stavares843 — APPROVED** [review]

**Pull request merged**
