### PR TITLE
feat(webrtc): basic video and voice calling

### PR DESCRIPTION
**Pull request by jpanay**
**What this PR does** 📖
Allows users to call each other with video and voice
**Which issue(s) this PR fixes** 🔨

Fixes #

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

### CODE REVIEW

**Review by Jekrimo — APPROVED** [review]

**Review by stavares843 — COMMENTED** [review]
Captura de ecrã 2021-12-14, às 22 56 41
Captura de ecrã 2021-12-14, às 22 56 47

should we comment out the fullscreen until we address that better?

**Comment by jpanay** [comment]
No need to comment it out because I'm going to continue to work on calling and bugs like this after this pull gets merged

**Comment by stavares843** [comment]
ohh k thanks for clarifying!  neat 🎉

**Comment by iltumio** [comment]
It is not working for me

**Comment by jpanay** [comment]
> It is not working for me

I just pulled dev and a bunch of files were moved around and cleared the work I did so that might be it, also fixing it now

**Pull request merged**
