### PR TITLE
fix(chat): focus on input after file upload

### PR DESCRIPTION
**Pull request by AlexZakablukov**
**What this PR does** 📖
focus on input after file upload

**Which issue(s) this PR fixes** 🔨
[AP-924](https://satellite-im.atlassian.net/browse/AP-924)

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

### CODE REVIEW

**Review by WanderingHogan — APPROVED** [review]

**Comment by phillsatellite** [comment]
Tested: Enter functionality works good, noticed that messages will not automatically move up in chat so user has to scroll after sending each message

https://user-images.githubusercontent.com/93608357/157915356-64c4678b-750f-4935-a57d-de4bb9ad61e1.mov

**Comment by AlexZakablukov** [comment]
> Tested: Enter functionality works good, noticed that messages will not automatically move up in chat so user has to scroll after sending each message
> 
>  chat.mov

the same behavior on dev, i think this issue for another task

**Review by stavares843 — CHANGES_REQUESTED** [review]
regarding the fix ''focus on input after file upload'' - is fixed on DM's but on groups still happens, do we need to add each fixed separately in groups as well going forward?

**Comment by molimauro** [comment]
Should be ok once we merge #1676 ;)

**Comment by stavares843** [comment]
https://github.com/Satellite-im/Core-PWA/pull/2326

**Pull request closed without merging**
