### PR TITLE
fix(user): prevent profile picture drag

### PR DESCRIPTION
**Pull request by josephmcg**
**What this PR does** 📖
title

**Which issue(s) this PR fixes** 🔨
AP-1538, AP-1554

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

### CODE REVIEW

**Comment by phillsatellite** [comment]
Issue was fixed 👍  Just out of curiosity is there anything we can do to avoid being able to highlight everything on the page? 
https://user-images.githubusercontent.com/93608357/168118949-2e1904fe-be41-421d-b7cb-510bf9414c61.mov

**Comment by josephmcg** [comment]
@phillsatellite sure, i removed user:select. I also went ahead and improved our device compatibility. some old browsers/devices still need vendor prefixes for that css rule, so I created a global class which applies all the prefixes

**Comment by phillsatellite** [comment]
@josephmcg thanks for adding that! It worked really well on Chrome and Brave but I was still having some issues getting it to work in Safari. I inspected the element in both Safari and Chrome (where it works) and I saw the same CSS is being applied so the extend psuedo element is doing it's thing, and also verified on MDN both my browsers should support user-select:none
Screen Shot 2022-05-13 at 11 18 11 AM (2)
Screen Shot 2022-05-13 at 11 18 11 AM

**Comment by josephmcg** [comment]
Since thats outside the scope of the original ticket, could we revisit that later?

**Comment by phillsatellite** [comment]
> Since thats outside the scope of the original ticket, could we revisit that later?
> 
> Also, whats the issue? The webkit version is getting applied to safari in your screenshot

Oh Im sorry I forgot to add the actual issue in the comment lol it was strange it said that it was being applied in inspect but when I would click and drag the profile picture it would still highlight everything 

https://user-images.githubusercontent.com/93608357/168403965-d3a897fa-8a10-4403-81f4-106c83807ba9.mov

**Comment by josephmcg** [comment]
I don't believe that's an issue. The user needs to be able to select text inside the chat

**Review by Jekrimo — APPROVED** [review]

**Review by WanderingHogan — APPROVED** [review]

**Review by stavares843 — CHANGES_REQUESTED** [review]
image

clicking on the profiles no longer works


image

works on dev

**Comment by stavares843** [comment]
issue no longer happens

**Review by stavares843 — APPROVED** [review]

**Pull request merged**
