### PR TITLE
fix(sidebar): change the add button position AP-674

### PR DESCRIPTION
**Pull request by davidchan1219**
**What this PR does** 📖

Changed the add button position in sidebar and slimbar

**Which issue(s) this PR fixes** 🔨

AP-674

### CODE REVIEW

**Comment by KemoPaw** [comment]
Screen Shot 2022-02-14 at 5 17 09 PM

Not sure if the "Plus Button" on the bottom right should be able to go over the current user's information section. Or this is an issue about not having enough active chats open, otherwise, it looks great! :)

**Review by stavares843 — CHANGES_REQUESTED** [review]
Captura de ecrã 2022-02-15, às 01 49 16

design doesn't have the button when theres no friends added

Captura de ecrã 2022-02-15, às 01 49 32

besides that clicking on the button doesn't do anything

**Comment by stavares843** [comment]
clicking on the add button should go to the add friends flow as liz mentioned

**Comment by davidchan1219** [comment]
@stavares843 Just fixed the issues you mentioned above

**Comment by phillsatellite** [comment]
Tested: When User selects the "New Chat +" or "home" at the top left, looks the word "Community" or "home" will appear behind the servers at the top
IMG_4653 3

**Comment by davidchan1219** [comment]
@phillsatellite When I set the tooltip position as top or others, that tooltip doesn't display, as of css issue.
I think we don't need to display the tooltip in the mobile view, when click any server. what do you think?

**Comment by phillsatellite** [comment]
@davidchan1219 Since we have the rest of the tooltips disabled on mobile for Alpha we could probably disable these as well cc: @stavares843 @WanderingHogan

**Comment by davidchan1219** [comment]
@phillsatellite okay, I disabled tooltip for mobile view

**Comment by stavares843** [comment]
i agree with @phillsatellite

**Review by phillsatellite — APPROVED** [review]

**Review by genie-magic — APPROVED** [review]

**Review by Jekrimo — APPROVED** [review]

**Review by stavares843 — APPROVED** [review]

**Pull request merged**
