### PR TITLE
chore(remove): cleanup of old files

### LINKED ISSUE #4971: Solana Cleanup
Removing unused files from the Solana folder

### PR DESCRIPTION
**Pull request by molimauro**
### What this PR does 📖
- title

### Which issue(s) this PR fixes 🔨
- Resolve #4971 
- General cleanup

### Additional comments 🎤
- SolanaManager tests skipped

### CODE REVIEW

**Comment by molimauro** [comment]
@iltumio can you please check if there are any Solana config we can remove and any functions in the SolanaManager we dont use anymore (like the requestAirdrop)? Thanks!

**Review by aewing — APPROVED** [review]

**Review by iltumio — APPROVED** [review]

**Comment by molimauro** [comment]
Why this is blocked @stavares843?

**Comment by josephmcg** [comment]
yeah this would be good to get in soon so we don't get more conflicts

**Comment by molimauro** [comment]
Its not related to this, seems a problem with the nodes

**Comment by stavares843** [comment]
will test locally instead 😅 thanks for taking a look

**Comment by molimauro** [comment]
Gonna merge this!

**Comment by stavares843** [comment]
🎉

**Pull request merged**
