### PR TITLE
refactor(user-profile): card style rework

### LINKED ISSUE #5127: Restore/rework user profile card's style

### PR DESCRIPTION
**Pull request by ThomBos**
### What this PR does 📖
- 

### Which issue(s) this PR fixes 🔨
- Resolve #5127

### CODE REVIEW

**Comment by ThomBos** [comment]
Schermata 2022-10-03 alle 15 30 22

this is before

Schermata 2022-10-03 alle 15 21 25

Schermata 2022-10-03 alle 15 23 19

Schermata 2022-10-03 alle 15 24 06

Schermata 2022-10-03 alle 15 24 14

this is after

Posted images, because this can't be tested since these elements are still unused on dev (might be added soon again)

Although wiring with iridium is almost done, it might need some more style work (opened to suggestions) that's the reason i opened this pr

**Comment by WanderingHogan** [comment]
@stavares843 can you check this out?

**Comment by stavares843** [comment]
🔨

**Comment by josephmcg** [comment]
I think allowing a user to view their own profile would be good so the user knows exactly what it looks like. The user can't get an exact idea of that based on the settings modal alone.

The only editable thing on the profile should be the note, imo

**Comment by ThomBos** [comment]
> I think allowing a user to view their own profile would be good so the user knows exactly what it looks like. The user can't get an exact idea of that based on the settings modal alone.
> 
> The only editable thing on the profile should be the note, imo

Ah good point, let's do it!
The only thing that i don't fully understand, why do we keep the note? I mean, i understand using it on other users, but is it needed if the profile is mine? i think i can only read my own notes, no?

**Review by josephmcg — CHANGES_REQUESTED** [review]
This isn't a full review, just a couple things i noticed while riding the train

**Comment by josephmcg** [comment]
i'm going to make a couple adjustments

**Comment by josephmcg** [comment]
- removed absolute positioning in favor of static
  - absolute is typically harder to manage across devices
- needed to apply overflow: hidden to a container for proper scroll behavior of the tab content. This overflow hidden would cause the negative margin on the image to get cut off. Went with a side by side display instead.
- removed image on mobile view. It looks fine on desktop, but it was difficult to fit it into mobile. Not sure if we even need this many pictures, realistically speaking. I feel like profile picture (inside the user circle) plus a profile banner would be plenty.

**Review by stavares843 — COMMENTED** [review]
image


i see the same profile

other user

image



any thoughts?

**Comment by josephmcg** [comment]
those are the quick profile and the settings profile, respectively. This profile is a separate modal. There's no render method implemented yet because it's not totally polished. You could add this line to QuickProfile if you want to see

```
        this.$store.commit('ui/setFullProfile', this.user)
```
something like this would be good

image

**Pull request merged**
