### PR TITLE
fix(glyph): fix some glyphs are returning 404

### PR DESCRIPTION
**Pull request by baymax-codecare**
**What this PR does** 📖
fix some glyphs are returning 404

**Which issue(s) this PR fixes** 🔨
AP-311

**Special notes for reviewers** 🗒️
This would fix AP-484 too.

### CODE REVIEW

**Review by stavares843 — APPROVED** [review]

**Review by WanderingHogan — APPROVED** [review]

**Comment by phillsatellite** [comment]
Tested: Only glyphs I had still appearing as a 404 were the last two in Genish Impact 2
Screen Shot 2022-02-01 at 4 15 29 PM (2)
Screen Shot 2022-02-01 at 4 15 56 PM

**Review by WanderingHogan — CHANGES_REQUESTED** [review]
@stavares843 found 2 more that need to be commented out

**Comment by stavares843** [comment]
feel free to remove the changes requested label and add the missing code review label again after addressing feedback 🔨 

thanks for updating 🔨

**Review by phillsatellite — APPROVED** [review]

**Review by josephmcg — APPROVED** [review]

**Review by WanderingHogan — APPROVED** [review]

**Pull request merged**
