### PR TITLE
fix replies push issue in chat history AP-77

### PR DESCRIPTION
**Pull request by davidchan1219**
**What this PR does** 📖

**Which issue(s) this PR fixes** 🔨

AP-77

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

### CODE REVIEW

**Review by Jekrimo — APPROVED** [review]

**Review by WanderingHogan — APPROVED** [review]
In the future, please make sure you have prettier and eslint installed and 'format document' this file so it's easier to understand

**Review by stavares843 — CHANGES_REQUESTED** [review]
https://user-images.githubusercontent.com/29093946/145239707-874ff98d-125a-436d-b720-38194520962e.mp4

the issue still happens in this branch

video above

**Comment by davidchan1219** [comment]
@stavares843 can you check it on AP-77 branch again?

**Comment by stavares843** [comment]
taking a look

**Review by stavares843 — COMMENTED** [review]
Captura de ecrã 2021-12-08, às 18 01 39

this code was already added on a previous PR

Captura de ecrã 2021-12-08, às 18 01 58

https://github.com/Satellite-im/Core-PWA/pull/566/commits/7c72f198256a55d05d69ed299cdd2ae435b1ab5b


closing this PR

**Comment by stavares843** [comment]
after adding the last dev branch here, files changed - 0

Captura de ecrã 2021-12-08, às 18 04 03

because this modification was already on dev

**Comment by stavares843** [comment]
fixed on dev, thanks! 🎉

**Pull request closed without merging**
