### PR TITLE
fix(settings): fix storage clear issue

### PR DESCRIPTION
**Pull request by davidchan1219**
**What this PR does** 📖

Fixed the storage clearing issue

**Which issue(s) this PR fixes** 🔨

AP-785

### CODE REVIEW

**Review by phillsatellite — APPROVED** [review]

**Review by WanderingHogan — CHANGES_REQUESTED** [review]
very minor change - since you are touching `store/settings/types.ts`, can you change the types to all lowercase, and do a `git reset HEAD cypress` before you push the change up

**Comment by WanderingHogan** [comment]
@davidchan1219 Good morning, you accidentally merged 'main' back to this instead of 'dev'

**Comment by WanderingHogan** [comment]
When you bring this up to date, please rebase from dev

**Pull request closed without merging**
