### PR TITLE
refactor(sidebar): use Nuxt link instead of button

### LINKED ISSUE #5274: switch sidebar to use NuxtLink component
makes everything faster and handles aria for you

### PR DESCRIPTION
**Pull request by josephmcg**
### What this PR does 📖
- use nuxt link for better prefetching, a11y, etc
- switch global anchor styles to only underline with specific class

### Which issue(s) this PR fixes 🔨
- Resolve #5274 

### Special notes for reviewers 🗒️
- 

### Additional comments 🎤
-

### CODE REVIEW

**Review by molimauro — APPROVED** [review]

**Review by stavares843 — COMMENTED** [review]
Captura de ecrã 2022-10-17, às 17 14 28

i tried 3x locally in dev, sign up in safari always works

tried 3x locally in this branch, always returns that error in safari, works in chrome

**Comment by WanderingHogan** [comment]
@stavares843 
I tried and this is working for me, maybe there is another issue locally for you. Can you try again removing node_modules, cleaning your yarn cache, removing the linked iridium folder, and re-running linkscript, yarn, and yarn dev

**Comment by stavares843** [comment]
shady

gonna try 🔨

**Comment by josephmcg** [comment]
Thats unrelated to anything I'm doing here. Are you on an older version of safari?

https://caniuse.com/broadcastchannel

**Comment by stavares843** [comment]
i'm using version 15 yes 😂

**Pull request merged**
