### PR TITLE
refactor(global): switch to comp api, remove unnecessary store value

### LINKED ISSUE #5378: upgrade global.vue to comp api

### PR DESCRIPTION
**Pull request by josephmcg**
### What this PR does 📖
- title
- render changelog based on local component state. no need to use store

### Which issue(s) this PR fixes 🔨
- Resolve #5378 

### Special notes for reviewers 🗒️
- 

### Additional comments 🎤
-

### CODE REVIEW

**Review by WanderingHogan — APPROVED** [review]
lgtm, but deferring to @molimauro 

@stavares843 or @phillsatellite can you try this PR and make sure it doesn't break any calling or modals (outside of the modal on the login page for changelog, which can still be accessed in settings)

**Comment by stavares843** [comment]
yes 🔨

**Comment by phillsatellite** [comment]
One thing I noticed when testing that I could replicate on Chrome, and Safari on Desktop but not mobile was whenever you call someone the PIP will appear as soon as you start call 

https://user-images.githubusercontent.com/93608357/197816591-5e7df835-45d1-4fab-872f-e9b9a488347f.mov

**Comment by josephmcg** [comment]
I see what's going on, the way I was accessing route was not reactive. will fix

**Comment by josephmcg** [comment]
there's some very weird reactivity issues going on here, gonna close for now

**Pull request closed without merging**
