### PR TITLE
refactor(chat): remove unnecessary code and fix intellisense

### PR DESCRIPTION
**Pull request by josephmcg**
**What this PR does** 📖
- add computed return types to fix `this` context, remove unnecessary $data and $props references
- remove unused data
- remove redundant prop

**Which issue(s) this PR fixes** 🔨
N/A

**Special notes for reviewers** 🗒️
- no new functionality, just code cleanup

**Additional comments** 🎤

### CODE REVIEW

**Review by molimauro — APPROVED** [review]

**Comment by molimauro** [comment]
🙏

**Comment by phillsatellite** [comment]
Found a small bug that I wasn't able to replicate on dev branch or test.satellite. Seems no matter if file sharing toggle is on or off user cannot send files in chat 

https://user-images.githubusercontent.com/93608357/167449085-285a0718-9970-4096-a7df-52613f245158.mov

**Comment by josephmcg** [comment]
in my haste I missed two instances of the old prop, should be fixed now

**Comment by stavares843** [comment]
thanks @josephmcg 🔨

**Review by phillsatellite — APPROVED** [review]

**Review by stavares843 — APPROVED** [review]

**Pull request merged**
