### PR TITLE
feat(sounds): play sounds only enabled AP-415

### PR DESCRIPTION
**Pull request by baymax-codecare**
**What this PR does** 📖
play sounds only when enabled on settings/notifications page

**Which issue(s) this PR fixes** 🔨

AP-415

**Special notes for reviewers** 🗒️
when commit jest check failed

**Additional comments** 🎤

### CODE REVIEW

**Comment by molimauro** [comment]
What about using something like:
```
const $Sounds = new SoundManager()
...
...

export default {
  playSound({ rootState }: ActionsArguments<UIState>, sound: any) {
    if (rootState.notificationsEnabled ) { // example
      $Sounds.playSound(Sounds.NEW_MESSAGE)
    }
  },
 ...
 }
 ```
 
we create an action for playing sounds instead of directly calling the `playSound` inside the class. We can access the state inside that action and check if we can play the sound. What do you think?

**Comment by baymax-codecare** [comment]
@molimauro  @WanderingHogan  I changed PR as you requested.
Plz review and give me opinion.

**Comment by WanderingHogan** [comment]
never merge

**Comment by WanderingHogan** [comment]
David, I am closing this. Please check https://github.com/Satellite-im/Core-PWA/pull/1173 and tell me if your changes are there.

**Pull request closed without merging**
