### PR TITLE
fix(modal): fix send money modal issue AP-470

### PR DESCRIPTION
**Pull request by genie-magic**
**What this PR does** 📖

fix send money modal issue

**Which issue(s) this PR fixes** 🔨

AP-470

### CODE REVIEW

**Comment by stavares843** [comment]
fixed ✅

**Review by stavares843 — APPROVED** [review]

**Review by Jekrimo — APPROVED** [review]

**Review by WanderingHogan — CHANGES_REQUESTED** [review]
two things - 

1. while you are in there can you add placeholders for the things vue is complaining about in the console, in 'WalletMiniBody' i think it's just
```
  data() {
    return {
      paymentOption: 'usd',
      accountID: '',
      searching: '',
    }
  },
  methods: {
    searchFriend() {
      //
    },
  },
  ```
  
  2. Can you look at how this change affects the send money modal in mobile view? I think it negatively affects mobile

**Comment by genie-magic** [comment]
> two things -
> 
> 1. while you are in there can you add placeholders for the things vue is complaining about in the console, in 'WalletMiniBody' i think it's just
> 
> ```
>   data() {
>     return {
>       paymentOption: 'usd',
>       accountID: '',
>       searching: '',
>     }
>   },
>   methods: {
>     searchFriend() {
>       //
>     },
>   },
> ```
> 
> 2. Can you look at how this change affects the send money modal in mobile view? I think it negatively affects mobile

@WanderingHogan  I fixed those 2 points.

**Review by WanderingHogan — APPROVED** [review]

**Comment by WanderingHogan** [comment]
@genie-magic thank you

**Pull request merged**
