### PR TITLE
fix(startup): do not await promises in accounts/startup

### PR DESCRIPTION
**Pull request by aewing**
**What this PR does** 📖
fixes the changes I made to the account startup (await)

**Which issue(s) this PR fixes** 🔨

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

### CODE REVIEW

**Review by molimauro — APPROVED** [review]

**Review by stavares843 — CHANGES_REQUESTED** [review]
Captura de ecrã 2022-05-16, às 22 03 25

i can't import an account on this branch

I tried locally and the netfly URL and was all the same

even the tests on Cypress can't import the account on this branch

it just gets stuck on loading

here's a seed 
entry soccer evoke oak bomb joke ugly safe spend arrest bacon remove

using dev just loads right away when importing the account

**Comment by stavares843** [comment]
any news? 🔨

**Review by WanderingHogan — APPROVED** [review]

**Comment by WanderingHogan** [comment]
@stavares843 can you give this a try again tomorrow?

**Comment by stavares843** [comment]
works now, both locally and on CI, thanks @WanderingHogan 🔨

**Pull request merged**
