### PR TITLE
refactor(webrtc): composable for active call timer

### LINKED ISSUE #5422: upgrade call timer components to script setup, use single composable
these two components share a lot of logic. upgrade both to script setup and create composable
components/views/media/heading/Heading.vue
components/views/chat/message/call/Call.vue

### PR DESCRIPTION
**Pull request by josephmcg**
### What this PR does 📖
- reuse shared logic

### Which issue(s) this PR fixes 🔨
- Resolve #5422 

### Special notes for reviewers 🗒️
- 

### Additional comments 🎤
-

### CODE REVIEW

**Comment by molimauro** [comment]
i think this should go also in `components/ui/BackgroundCall/BackgroundCall.vue` or am i wrong?

**Comment by josephmcg** [comment]
Good catch, i can add that next week

**Comment by drepram** [comment]
If I may help, I could add the change :D

**Review by molimauro — APPROVED** [review]
Nice!

**Review by phillsatellite — APPROVED** [review]

**Pull request merged**
