### PR TITLE
fix(chat): block sending empty message on quick profile

### PR DESCRIPTION
**Pull request by genie-magic**
**What this PR does** 📖
block sending an empty message on the quick profile

**Which issue(s) this PR fixes** 🔨

AP-1101

### CODE REVIEW

**Review by josephmcg — CHANGES_REQUESTED** [review]
try using an empty regex instead, I put one in the config.ts.
This implementation would allow a message of spaces

`if (this.$Config.regex.empty.test(this.text))`

**Comment by genie-magic** [comment]
> try using an empty regex instead, I put one in the config.ts. This implementation would allow a message of spaces
> 
> `if (this.$Config.regex.empty.test(this.text))`

Thanks.

**Comment by josephmcg** [comment]
We may want to show some type of error message, otherwise the user may be confused

**Comment by genie-magic** [comment]
> We may want to show some type of error message, otherwise the user may be confused. maybe something like `Message must contain at least one non-space character`

I added that too. Thanks for your suggestion. we may need to add that to main chatbar too.

**Review by molimauro — APPROVED** [review]

**Review by phillsatellite — APPROVED** [review]

**Comment by stavares843** [comment]
Captura de ecrã 2022-03-22, às 17 25 22

the error is not dismissed when user already entered a valid char

**Review by stavares843 — APPROVED** [review]

**Review by molimauro — APPROVED** [review]

**Pull request merged**
