### PR TITLE
fix(chat): change message hover

### PR DESCRIPTION
**Pull request by AlexZakablukov**
**What this PR does** 📖
fix hover on preview image

**Which issue(s) this PR fixes** 🔨
[AP-1015](https://satellite-im.atlassian.net/browse/AP-1015)

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

### CODE REVIEW

**Review by Jekrimo — APPROVED** [review]

**Review by molimauro — APPROVED** [review]

**Comment by AlexZakablukov** [comment]
fixed

**Comment by phillsatellite** [comment]
Tested: One more little bug happened when changes were added. If you go into the preview the background is not as dark as it should be. If you move your curser outside of browser window it'll temporarily change the background to what it should be 

https://user-images.githubusercontent.com/93608357/157954876-30d153d5-e7ca-4011-9afa-98f0f54b8e96.mov

**Comment by AlexZakablukov** [comment]
fixed

**Review by phillsatellite — APPROVED** [review]

**Review by WanderingHogan — APPROVED** [review]

**Comment by molimauro** [comment]
Sorry @stavares843 didnt see the review req, my fault

**Comment by stavares843** [comment]
no worries, thanks for reviewing 🔨

**Review by stavares843 — APPROVED** [review]

**Pull request merged**
