### PR TITLE
fix(images): heic type not always detected

### PR DESCRIPTION
**Pull request by molimauro**
**What this PR does** 📖
Fix HEIC images detection

**Which issue(s) this PR fixes** 🔨
AP-1077

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

### CODE REVIEW

**Review by WanderingHogan — APPROVED** [review]

**Review by phillsatellite — APPROVED** [review]

**Review by stavares843 — APPROVED** [review]

**Comment by stavares843** [comment]
thanks for updating the test as well 🔨

**Review by stavares843 — CHANGES_REQUESTED** [review]
Captura de ecrã 2022-03-15, às 23 54 23

strange i can't upload a .heic file on this branch on files section, other files like jpeg works fine

works fine on dev

Captura de ecrã 2022-03-15, às 23 54 40

flow
- go to this branch
- files
- upload heic
- gets stuck on loading and never sents the image
- upload other file like jpeg
- file appears uploaded
- go to dev
- files
- upload heic
- file gets uploaded

**Comment by josephmcg** [comment]
I noticed weird bugs when I was just checking the MIME type as well. I think @genie-magic setup the HEIC check based on byte values. Eric, could you explain why you did it that way?

**Comment by genie-magic** [comment]
> I noticed weird bugs when I was just checking the MIME type as well. I think @genie-magic setup the HEIC check based on byte values. Eric, could you explain why you did it that way?
> 
> After alpha, I'd like to check byte value for all files rather than relying on MIME type (AP932)

Heic file is only able to detectable with byte check... not all heic file return type image/heic... some files return its type empty string.

**Comment by josephmcg** [comment]
Filesystem is working fine on dev for me, but I see chat upload is a little buggy.
Probably related to this forEach in the async handleFile function. I got around this by using a `for await`, feel free to borrow that in the Upload.vue rework

image

image

**Comment by molimauro** [comment]
> > I noticed weird bugs when I was just checking the MIME type as well. I think @genie-magic setup the HEIC check based on byte values. Eric, could you explain why you did it that way?
> > After alpha, I'd like to check byte value for all files rather than relying on MIME type (AP932)
> 
> Heic file is only able to detectable with byte check... not all heic file return type image/heic... some files return its type empty string.

Not always true unfortunately. Some HEIC where not properly detected only with byte value

**Comment by josephmcg** [comment]
I wonder if the HEIC that aren't detected via byte value have been converted from another format. I would assume checking byte value is the most accurate way

**Comment by genie-magic** [comment]
> I wonder if the HEIC that aren't detected via byte value have been converted from another format. I would assume checking byte value is the most accurate way

yes.. that's why I chose byte checking.

**Comment by molimauro** [comment]
> I wonder if the HEIC that aren't detected via byte value have been converted from another format. I would assume checking byte value is the most accurate way

Its a photo i took with my iPhone and sent to my Mac via Airdrop

**Comment by molimauro** [comment]
I forgot to update a function for the thumbnails but it seems that my heic image is not previewing correctly in the file section (maybe because its .HEIC instead of .heic?). This is the image that is not recognized as HEIC with the byte check: https://we.tl/t-PkP1zcbmvA

**Comment by molimauro** [comment]
> Works well with genuine heic, but crashes on what I assume is a converted one. This is a file Phil sent me for testing https://we.tl/t-v6u0yMMoKx

On dev this is not recognized as valid heic right?

**Comment by josephmcg** [comment]
correct, that evaluates false on dev isHeic check. Looking at the headers, it's a converted png
https://www.fileformat.info/tool/hexdump.htm

**Comment by molimauro** [comment]
So i had a quick chat with Joe and we can stick to the current implementation based on bytes check. Still it is not perfect of course but i'll create a ticket for the future, we'll need to find a proper library to handle all these formats. Thanks everyone!

**Pull request closed without merging**
