### PR TITLE
fix(modal): changelog modal style

### PR DESCRIPTION
**Pull request by molimauro**
### What this PR does 📖
- Fix the style for the changelog modal

### Which issue(s) this PR fixes 🔨
- Resolve #

### CODE REVIEW

**Comment by stavares843** [comment]
Captura de ecrã 2022-09-19, às 17 05 36
Captura de ecrã 2022-09-19, às 17 05 46


if the browser is a little bit smaller, the got it button is hidden and there's no scroll


not against merging, way better compared with prod

**Comment by molimauro** [comment]
Nah i'll fix that thanks :)

**Comment by josephmcg** [comment]
Nathan fixed this issue and consolidate some of the basic modals [here](https://github.com/Satellite-im/Core-PWA/pull/4942).

We should try to work on specific github issues so we don't step on each other's toes

**Comment by molimauro** [comment]
Sorry @josephmcg i know, it was on Friday and i tried to put a patch for the early access

**Comment by molimauro** [comment]
But dope, the modals needed a refactor ;)

**Comment by stavares843** [comment]
Captura de ecrã 2022-09-21, às 21 34 39


nathan's fix is also cool, can we update the icon instead of the ''x'' there? @josephmcg

**Pull request closed without merging**
