### PR TITLE
fix(images): multi upload hopeful fix

### PR DESCRIPTION
**Pull request by Jekrimo**
**What this PR does** 📖
Fixes multi upload hopefully

**Which issue(s) this PR fixes** 🔨
274

### CODE REVIEW

**Review by stavares843 — CHANGES_REQUESTED** [review]
https://user-images.githubusercontent.com/29093946/147296775-6ba643fa-84a6-438f-8c18-0b98708684f4.mp4


trying to send 4 only sends 2

Chrome, macOS

**Comment by stavares843** [comment]
Captura de ecrã 2021-12-27, às 17 46 07

the cancel/send buttons are not appearing when copy-pasting the images

**Comment by Jekrimo** [comment]
> Captura de ecrã 2021-12-27, às 17 46 07
> 
> the cancel/send buttons are not appearing when copy-pasting the images

Yup, I saw this too after rebasing dev. Something happened with the side menu, if you close that menu the buttons are still there. I need to ask in dev chat who changed styles for the side menu as I spent 2 hours trying to fix and couldn't figure out what was done

**Comment by stavares843** [comment]
thanks for checking!

**Comment by stavares843** [comment]
note - UI changed with this PR - [#791](https://github.com/Satellite-im/Core-PWA/pull/791)



image

**Comment by stavares843** [comment]
@Jekrimo [#791](https://github.com/Satellite-im/Core-PWA/pull/791) merged

**Comment by stavares843** [comment]
trying to send 4, sends 1 and gets stuck on loading

Chrome, macOS

**Pull request closed without merging**
