### PR TITLE
feat(files): File system functionality AP-469

### PR DESCRIPTION
**Pull request by josephmcg**
**What this PR does** 📖
- implement new file system class
- create folders and files. When uploading files, it's currently just ripping some data (name, size) and saving that. Actual file needs to be uploaded to textile and then store the hash.
  - nsfw filter for file upload
  - proper error handling/notification if you try to add a file with the same name
  - went with new upload design to handle multiple files more easily and improve ux (confirmed with Liz)
- traverse directories
- liked status toggle for folders/files. Map has funky reactivity for Vue2, so I had to do a workaround to force render

**Which issue(s) this PR fixes** 🔨
AP-469, AP-640

**Special notes for reviewers** 🗒️
- removed the fileSystem from the Bucket class. It seemed unnecessary, since we already have the FileSystem global we can use. Bucket will store the export
- switched up the Fil constructor and fs.createFile to make it easier to use (objects rather than regular params). updated tests accordingly
- we may consider switching the children map on Directory to an array for better reactivity with Vue2. I've implemented hacky workarounds for any issues so far, but may not scale well (depending on how many reactive updates these items need to support). Vue3 supports Map once we upgrade
https://stackoverflow.com/questions/37130105/does-vue-support-reactivity-on-map-and-set-data-types

**Additional comments** 🎤

### CODE REVIEW

**Comment by josephmcg** [comment]
@RetroPronghorn Right on, just added

**Review by RetroPronghorn — APPROVED** [review]

**Comment by WanderingHogan** [comment]
@stavares843 @phillsatellite there isn't much to test here other than the app doesn't crash, with the uploading and management of files coming soon

**Review by stavares843 — CHANGES_REQUESTED** [review]
image

crash's when uploading a .heic file, standard image on iOS

**Review by stavares843 — CHANGES_REQUESTED** [review]
Captura de ecrã 2022-02-16, às 18 11 22

same crash, with the .TIFF file

**Comment by stavares843** [comment]
i know its all the same crash but added in case it was useful info 🔨

**Comment by josephmcg** [comment]
Thanks Sara, I'll work on supporting these file types

**Comment by josephmcg** [comment]
This is happening because nsfwjs can only scan a select few image types. The chat image upload is running into the same problem, but its wrapped in a try catch that marks any image unable to be scanned as nsfw. I think I'll refactor the nsfw scan function to only check supported file types to avoid a runtime error and provide proper support for people who want to sent/upload tiff

image

image

**Comment by josephmcg** [comment]
@stavares843 ready for testing again. We won't allow tiff for now, but I will resolve that in AP-807 later. heic should work though. And we should block the upload if the file is an image that can't be scanned for any reason

**Comment by stavares843** [comment]
thanks 🔨

**Pull request merged**
