### PR TITLE
fix(friends): online status is hidden if not friend

### PR DESCRIPTION
**Pull request by vimercati-samir**
What this PR does 📖
Hide online status of an user if not a friend

Which issue(s) this PR fixes 🔨
[AP-1820](https://satellite-im.atlassian.net/browse/AP-1820)

Special notes for reviewers 🗒️

Additional comments 🎤

### CODE REVIEW

**Review by phillsatellite — APPROVED** [review]

**Review by molimauro — APPROVED** [review]

**Review by stavares843 — CHANGES_REQUESTED** [review]
dev vs this branch

Screenshot 2022-06-17 at 17 23 50

Screenshot 2022-06-17 at 17 23 32

**Comment by vimercati-samir** [comment]
> dev vs this branch
> 
> Screenshot 2022-06-17 at 17 23 50
> 
> Screenshot 2022-06-17 at 17 23 32

Should be resolved in commit 020de50dff1ba2d9e12b9bb6515544e1173b0ebe

**Review by josephmcg — CHANGES_REQUESTED** [review]
I think it would be simpler to just render UiCircle rather than UiUserState inside the friend component if send prop is true
components/views/friends/friend/Friend.html

What you're doing here is essentially forcing UiUserStateto render as if it were UiCircle. Also always add typescript return annotation to computed

**Comment by vimercati-samir** [comment]
> I think it would be simpler to just render UiCircle rather than UiUserState inside the friend component if send prop is true components/views/friends/friend/Friend.html
> 
> What you're doing here is essentially forcing UiUserState to render as if it were UiCircle. Also always add typescript return annotation to computed

Agreed, changed accordingly in commit 68949dad6be2d2d1aa97bb4af1ced03cc33bc216

**Review by stavares843 — APPROVED** [review]

**Pull request merged**
