### PR TITLE
feat(Themes): added custom flair color selector

### PR DESCRIPTION
**Pull request by RetroPronghorn**
**What this PR does** 📖

Allows user to choose custom flair color on some themes.
localhost_3000_(iPhone X) (14)

image

### CODE REVIEW

**Review by Jekrimo — APPROVED** [review]

**Review by molimauro — APPROVED** [review]

**Review by phillsatellite — APPROVED** [review]

**Comment by stavares843** [comment]
Captura de ecrã 2021-12-27, às 20 07 23

profile > timezone > still shows the blue background when searching

**Comment by stavares843** [comment]
Captura de ecrã 2021-12-27, às 20 07 33

should the cursor be matching the theme as well?

**Comment by stavares843** [comment]
should the search/filter match the theme as well?

Captura de ecrã 2021-12-27, às 20 12 19

**Comment by stavares843** [comment]
should the reply to match the theme as well?

Captura de ecrã 2021-12-27, às 20 13 42
l

**Comment by stavares843** [comment]
Captura de ecrã 2021-12-27, às 20 14 02

should the border on the edit box match the theme?

**Comment by stavares843** [comment]
Captura de ecrã 2021-12-27, às 20 14 33

when selecting text, should match the theme?

**Review by stavares843 — CHANGES_REQUESTED** [review]
pretty neat! 🎉 

added couple comments

**Pull request merged**
