### PR TITLE
fix(reply): reply on reply works, fix slice bug

### PR DESCRIPTION
**Pull request by Jekrimo**
**What this PR does** 📖
Allows a reply button on replies in a thread. Currently they just reply to that convo, ticket was created to loook into nesting thread replies - AP-1282

Also fixes a bug introduced in a switch of typings for .slice() - groups should have a custom bubble icon for 3+ chatters.

**Which issue(s) this PR fixes** 🔨

AP-1183

### CODE REVIEW

**Comment by phillsatellite** [comment]
Tested: I see the option to reply on a reply, but seems bug when hovering over a reply the reaction button will stay visible on original message 

https://user-images.githubusercontent.com/93608357/161163543-b1cf5b30-178a-4861-aa7e-f7334e608fb8.mov

**Comment by phillsatellite** [comment]
Okay that bug is gone! 💥  I did stumble over one more little thing on this PR I can edit a reply but not if it is responding to a gif 
Screen Shot 2022-04-01 at 3 21 12 PM
responding to gif 
Screen Shot 2022-04-01 at 3 21 25 PM

**Comment by Jekrimo** [comment]
> 

Does that only happen on this branch and it's fine on the others?

**Comment by Jekrimo** [comment]
I'm workin on at least getting the edit button for replies to work now, so lets leave this one open until I can get that working, but make a story for gif bugs on replies, that's going to be something dif for sure. <3

**Comment by phillsatellite** [comment]
Hi @Jekrimo ! I tested again and only found one little small bug that I think hopefully is a easy fix lol Shoot me a DM if you need me to go into detail about it more
So bug is: 
If User A sends a message, and User B replies to it, the edit message button will appear on both messages for User A and will not appear at all for User B. 

https://user-images.githubusercontent.com/93608357/162089095-5498a628-a786-4943-9cde-68738df4f285.mov

**Pull request closed without merging**
