### PR TITLE
fix: fix mobile cut off phrases on import account AP-159

### PR DESCRIPTION
**Pull request by genie-magic**
**What this PR does** 📖
fix mobile cut off phrases on import account
**Which issue(s) this PR fixes** 🔨

Fixes # AP-159

### CODE REVIEW

**Review by WanderingHogan — APPROVED** [review]

**Review by Jekrimo — APPROVED** [review]

**Review by WanderingHogan — CHANGES_REQUESTED** [review]
Can you add something like `overflow-wrap: break-word;` to the css for the actual text in the little pills

**Comment by genie-magic** [comment]
> overflow-wrap: break-word;

@WanderingHogan  How about adding white-space: break-spaces instead of overflow-wrap: break-word ?

**Comment by WanderingHogan** [comment]
@genie-magic if that works, then sure. I was just guessing what might break the words into newlines 😃

**Comment by WanderingHogan** [comment]
@stavares843 fixed the merge conflicts, and now that we are using bip lists we dont need to re-work this to wrap the text. We are only using bip39, the longest words across all 9 languages are only 8 characters, here is a long word from each language:

english: 8 characters
japanese: ぎじにってい
korean: 홈페이지
spanish: asegurar
chinese simplified: 艇
chinese traditional: 患
french: académie
italian: accusato
czech: amputace

**Review by RetroPronghorn — APPROVED** [review]

**Review by WanderingHogan — APPROVED** [review]

**Comment by stavares843** [comment]
using a SE, 8 chars, lacks a bit padding on the close icon but gonna merge this anyway and that can be improved later

Captura de ecrã 2021-12-15, às 13 13 39

**Pull request merged**
