### PR TITLE
fix(chat): focus on text input after image upload

### PR DESCRIPTION
**Pull request by AlexZakablukov**
**What this PR does** 📖
focus on text input after image upload

**Which issue(s) this PR fixes** 🔨
[AP-804](https://satellite-im.atlassian.net/browse/AP-804)

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

### CODE REVIEW

**Review by KemoPaw — APPROVED** [review]
Working snazzy! 🎉

**Review by josephmcg — CHANGES_REQUESTED** [review]
Do we want to add auto focus after drag + drop a file too? We can do that in another ticket if it makes more sense

**Comment by AlexZakablukov** [comment]
I think it is ok that it autofocus after drag and drop, should I change something?

**Comment by WanderingHogan** [comment]
@josephmcg this is okay

**Pull request merged**
