### PR TITLE
feat(jest): 100% coverage for GroupChatsProgram.types

### PR DESCRIPTION
**Pull request by drepram**
**What this PR does** 📖

Self-explanatory

**Which issue(s) this PR fixes** 🔨

AP-2146

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

### CODE REVIEW

**Comment by stavares843** [comment]
Captura de ecrã 2022-08-15, às 14 08 26

failing on CI 🔨

**Review by stavares843 — COMMENTED** [review]
added comment

**Comment by drepram** [comment]
> added comment

fixed!

**Comment by stavares843** [comment]
Captura de ecrã 2022-08-15, às 14 25 39

failing 🔨

**Comment by drepram** [comment]
> Captura de ecrã 2022-08-15, às 14 25 39
> 
> failing 🔨

Fixed again!

**Pull request merged**
