### PR TITLE
feat(jest): 100% coverage for Directory.ts

### PR DESCRIPTION
**Pull request by drepram**
**What this PR does** 📖

Self-explanatory; this is an increase.

**Which issue(s) this PR fixes** 🔨

Using the `AP-549` ticket again :)

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

### CODE REVIEW

**Review by josephmcg — APPROVED** [review]

**Review by stavares843 — CHANGES_REQUESTED** [review]
Captura de ecrã 2022-03-14, às 12 45 21

this branch

vs dev
Captura de ecrã 2022-03-14, às 12 45 55

can you pls check why libraries/Textile/BucketManager.test.ts takes 5s in this branch?

**Comment by josephmcg** [comment]
@stavares843 I'm not encountering that issue, about 3 seconds total. Could we get a third opinion?

**Comment by drepram** [comment]
All seems alright? 
image

**Comment by stavares843** [comment]
the issue is always reproducible on my side

please don't change labels if there are no new commits

**Comment by stavares843** [comment]
the CI is not having that issue but locally on my side takes those extra seconds, and on dev doesn't happen

**Review by stavares843 — APPROVED** [review]

**Comment by stavares843** [comment]
strange, is no longer getting slow 

i will let you know if happens again

**Pull request merged**
