### PR TITLE
fix(online-user-indicator): removed indicator when the app is still lo…

### PR DESCRIPTION
**Pull request by ThomBos**
**What this PR does** 📖
removes online indicator when chat's is loading
**Which issue(s) this PR fixes** 🔨
AP-1835

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

### CODE REVIEW

**Review by molimauro — APPROVED** [review]

**Comment by phillsatellite** [comment]
Found small bug when testing, when you load into account works as should, if you navigate to files and/or friends and then back to chat "user not connected" will appear while chat is still loading 

https://user-images.githubusercontent.com/93608357/176939149-816f4b68-926a-4740-b5f5-a21423303cb2.mov

**Review by molimauro — APPROVED** [review]

**Comment by ThomBos** [comment]
> what phil mentioned above still happens
> 
> seed end electric swear hurdle business priority salad ancient wire change please purpose

i'm not having the same issue at all... gotta import "bug-finder n1" account...

**Comment by stavares843** [comment]
> gotta import "bug-finder n1" account...

😂

**Comment by josephmcg** [comment]
this is looking at textile state which will be removed, closing

**Pull request closed without merging**
