### PR TITLE
feat(toast): add error toast styling

### PR DESCRIPTION
**Pull request by jasonwoodland**
**What this PR does** 📖
Makes error toasts red

**Which issue(s) this PR fixes** 🔨
AP-1639

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

### CODE REVIEW

**Review by josephmcg — CHANGES_REQUESTED** [review]
fine with me, but let's confirm with Liz

**Review by stavares843 — COMMENTED** [review]
agree with Joe,

also, is this for only error toasts or also the informative ones? example when we copy a ID on the friends section

**Comment by jasonwoodland** [comment]
@stavares843 the copying id one is still blue, just the toasts called with `$toast.error` will appear red

**Review by WanderingHogan — APPROVED** [review]

**Comment by WanderingHogan** [comment]
easy to overwrite in any theme, uses var, good job!

**Comment by WanderingHogan** [comment]
you can test this with `window.$nuxt.context.$toast.error('hi')` in the chrome console

**Review by stavares843 — APPROVED** [review]

**Comment by stavares843** [comment]
thanks @WanderingHogan 🔨

**Pull request merged**
