### PR TITLE
refactor(enhancers): upgrade enhancers templates, move reaction store…

### LINKED ISSUE #5361: refactor enhancers

### PR DESCRIPTION
**Pull request by josephmcg**
… to chat instead of ui

### What this PR does 📖
- improve enhancers html templates. iterate rather than copy/paste
- ui vuex store module is a bit of a monolith. I moved some enhancer related values to chat module to keep things more organized. Also simplified store whenever possible. I'd like to move this to compositions eventually, but we need to upgrade all these components first
- simplify ui mutations tests. pull in default store value rather than declaring a more specific mock
  - I deleted a couple tests related to the emoji/glyph usage. I did this because we want to move this to iridium so it's consistent across devices.
- upgraded a few components to comp api
- organize vuex persist list by module. remove legacy values that no longer exist 

### Which issue(s) this PR fixes 🔨
- Resolve #5361 

### Special notes for reviewers 🗒️
- edit message emoji button is still broken, I will fix that here https://github.com/Satellite-im/Core-PWA/issues/5355

### Additional comments 🎤
-

### CODE REVIEW

**Review by molimauro — APPROVED** [review]

**Review by phillsatellite — APPROVED** [review]

**Review by stavares843 — COMMENTED** [review]
Captura de ecrã 2022-10-21, às 18 16 49

@josephmcg does this seems related to the PR?

**Comment by josephmcg** [comment]
Could you tell me anything about the flow you used to create it? I think old store values had a 'show' boolean. If you didnt restart nuxt this might happen

**Comment by stavares843** [comment]
the CI is having this issue when entering the app

video below


https://user-images.githubusercontent.com/29093946/197343626-8e02bd5e-47a0-45da-aaf0-bce3c029ef0c.mp4

but I couldn't reproduce this on my side, but is always happening on this PR

all the other PR's are fine

**Comment by stavares843** [comment]
all green now 🎉 

thanks @josephmcg 🔨

**Review by stavares843 — APPROVED** [review]

**Pull request merged**
