### PR TITLE
feat(files): upload files to ipfs

### PR DESCRIPTION
**Pull request by maljuburi**
### What this PR does 📖
- Utilizes the updated file upload functionality on Iridium https://github.com/Satellite-im/iridium/pull/114
- We upload files to IPFS now and we allow large file uploads

### CODE REVIEW

**Review by molimauro — APPROVED** [review]

**Comment by molimauro** [comment]
DOPE!

**Review by stavares843 — DISMISSED** [review]
Captura de ecrã 2022-10-05, às 13 59 39

returns error trying to upload


files are just screenshots with 2 mbs

**Comment by stavares843** [comment]
@WanderingHogan do you know if the nodes are updated on fleek? 🔨

**Comment by WanderingHogan** [comment]
@stavares843 I added the merged block label until the iridium update is merged so you can check it out again

**Comment by stavares843** [comment]
thanks @WanderingHogan 🔨

**Pull request merged**
