### PR TITLE
chore(packageJson): update package deps, move dev deps

### PR DESCRIPTION
**Pull request by aewing**
**What this PR does** 📖
Updates package semvers in package.json where possible without friction

**Which issue(s) this PR fixes** 🔨
[AP-937](https://satellite-im.atlassian.net/browse/AP-937)

**Special notes for reviewers** 🗒️
Messaging test snapshot was failing with a one-off on the setInterval index, so I updated that snapshot.

### CODE REVIEW

**Review by stavares843 — CHANGES_REQUESTED** [review]
Captura de ecrã 2022-02-28, às 22 27 38

it gets stuck there when trying to build this branch locally

even with the new server was the same

**Comment by aewing** [comment]
> Captura de ecrã 2022-02-28, às 22 27 38
> 
> it gets stuck there when trying to build this branch locally
> 
> even with the new server was the same

ok, did you run `yarn` after pulling the branch after pulling? 
what steps did you take to see this result? on which operating system?

**Comment by stavares843** [comment]
the steps I use for every branch

- git checkout branch
- yarn
- yarn dev


and then when building, gets stuck on loading and returns error on the browser console

I'm using an M1, Monterey

**Comment by aewing** [comment]
> the steps I use for every branch
> 
> * git checkout branch
> * yarn
> * yarn dev
> 
> and then when building, gets stuck on loading and returns error on the browser console
> 
> I'm using an M1, Monterey

definitely not seeing that locally -- what node + yarn version?

**Comment by stavares843** [comment]
node
v16.13.1

yarn
1.22.17


this compiles fine on dev and on the other branch's

**Comment by stavares843** [comment]
checking again

**Comment by stavares843** [comment]
git pull
yarn
yarn dev


same error

**Comment by aewing** [comment]
> this compiles fine on dev and on the other branch's
I don't doubt it, just trying to understand why. It builds and compiles fine on my machine with the same node and yarn version. I have tried clearing .nuxt/ and node_modules/ but it still works fine for me. It also deployed the preview without issue, so I'm just trying to narrow down the cause.

Which browser & version? Anything you can think of that might be a cause?

**Comment by stavares843** [comment]
Chrome, 98.0.4758.109 version

I don't know what's the reason for the error. Another member of the QA team also tried, with the same setup and was the same for him as well.

**Comment by WanderingHogan** [comment]
try:
`yarn cache clean`
`rm yarn.lock`
`rm -rf node_modules`

**Review by WanderingHogan — APPROVED** [review]
Looks good to me once @stavares843 is satisfied

**Comment by stavares843** [comment]
thanks for fixing the conflict 🔨 just testing a bit more and then will get this merged

**Review by phillsatellite — APPROVED** [review]

**Review by stavares843 — APPROVED** [review]

**Review by stavares843 — APPROVED** [review]

**Pull request merged**
