### PR TITLE
feat(quickProfile): improve quickProfile ui/ux

### LINKED ISSUE #4965: quick profile style/ux improvements
- add click behavior to user avatar in chat Message
- add more space to overflow behavior
- add quickprofile to groupSidebar click

### PR DESCRIPTION
**Pull request by josephmcg**
### What this PR does 📖
- add click hander on Message avatar
- improve overflow logic so it doesn't hug the edge of the screen
- add click handlers and hover state on group chat sidebar

### Which issue(s) this PR fixes 🔨
- Resolve #4965

### CODE REVIEW

**Review by molimauro — APPROVED** [review]

**Review by phillsatellite — APPROVED** [review]

**Review by stavares843 — CHANGES_REQUESTED** [review]
if the username has some more chars, get cut off

Captura de ecrã 2022-09-22, às 19 33 56


also, if you try to message a user from the group chat that is not your friend, trying to send a message doesn't do anything

image

**Comment by phillsatellite** [comment]
Just a quick question, are we going to add this and the rest of the group sidebar into mobile at a later time? Wasn't sure if this is intended just for Desktop. Thanks Joe! 
https://user-images.githubusercontent.com/93608357/191826779-fb722202-588c-4e50-801c-195d8879c08e.mp4

**Comment by josephmcg** [comment]
I fixed the overflow issue and removed the message input unless the user is your friend. Maybe we will add DM functionality for users that aren't friends eventually, but this seemed like the simplest fix for now.

I would like to add this as a third swiper slide on mobile, I'll make a ticket for that

**Comment by stavares843** [comment]
thanks @josephmcg 🔨

**Comment by stavares843** [comment]
Captura de ecrã 2022-09-26, às 13 48 14

made a group, all those are added as friends but clicking on any of them doesn't show the quick profile

**Comment by josephmcg** [comment]
I didnt touch that code. Did you restart nuxt after switching branches?

**Comment by stavares843** [comment]
which should be updated, unless both doesn't wanna work 😂

**Pull request merged**
