### PR TITLE
test(cypress): add tests for videocall pair chat

### PR DESCRIPTION
**Pull request by luisecm**
**What this PR does** 📖
- Adding cypress tests for integration pair chat on chat-first-users.js and chat-second-user.js to test videocall flows
- Added data-cy attributes where needed for videocall DOM elements
- Covering several flows in videocall and functionality of mute audio, video, remote audio and screen share buttons

**Which issue(s) this PR fixes** 🔨
AP-1520

**Special notes for reviewers** 🗒️
- No videos for now, since I was not able to thoroughly test both accounts at the same time due to textile issues. We need to run npm run cy:chat to execute these tests in parallel
- If timing issues are presented when running both tests at the same time, I will update timeouts and cy.wait values if needed.
- Sending this one as draft in case that changes are required

**Additional comments** 🎤

Cypress Video First User:
https://user-images.githubusercontent.com/35935591/174675379-4657bfb7-2fb2-4858-8d75-7e794d299bd4.mp4

Cypress Video Second User:
https://user-images.githubusercontent.com/35935591/174675383-be047fba-da82-41e9-abbf-67332a98e30b.mp4

Tests Passed:
image

### CODE REVIEW

**Review by phillsatellite — APPROVED** [review]

**Comment by stavares843** [comment]
local

Captura de ecrã 2022-05-31, às 21 11 20
Captura de ecrã 2022-05-31, às 21 11 30

CI

Captura de ecrã 2022-05-31, às 21 11 43
Captura de ecrã 2022-05-31, às 21 11 53

**Review by stavares843 — CHANGES_REQUESTED** [review]
added comment 🔨

**Comment by stavares843** [comment]
could be due to the last updates we added related to video calls 💥

**Comment by stavares843** [comment]
closing, will reopen later

**Review by stavares843 — APPROVED** [review]

**Pull request merged**
