### PR TITLE
fix(eslint): Persist uploaded chat images during session AP-113

### PR DESCRIPTION
**Pull request by josephmcg**
**What this PR does** 📖
- persist uploaded images if the user switches chats or goes to friends list/files page
- clean up eslint error related to filter expecting return

**Which issue(s) this PR fixes** 🔨
AP-113

**Special notes for reviewers** 🗒️

**Additional comments** 🎤
- I would like to refactor Upload.vue when things aren't as busy

### CODE REVIEW

**Comment by josephmcg** [comment]
@molimauro which button do you mean? I typically hit [enter] or the send arrow on the right

image

**Comment by molimauro** [comment]
@josephmcg sorry i meant the "+" button. I dont like very much that the preview is descendant of that button, what do you think?

**Comment by josephmcg** [comment]
@molimauro Oh yeah I see what you mean, I completely agree. I try to avoid absolute whenever I can.
I'll make a ticket for that right now

**Comment by molimauro** [comment]
@josephmcg oh sweet thank you! yeah i was waiting for these changes before make this refactor because it's easy with files in the store.

**Review by phillsatellite — APPROVED** [review]

**Review by stavares843 — APPROVED** [review]

**Pull request merged**
