### PR TITLE
AP-235 Chat - We should persist the replies when switching conversations

### PR DESCRIPTION
**Pull request by davidchan1219**
**What this PR does** 📖

**Which issue(s) this PR fixes** 🔨

AP-235

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

### CODE REVIEW

**Review by stavares843 — CHANGES_REQUESTED** [review]
doesn't work here

when going to a chat, writing a reply, changing chat, going again to the previous one the reply is not there

https://user-images.githubusercontent.com/29093946/145442320-11438de8-6d0c-4de7-98c4-1a0a5af30e22.mp4

**Comment by RetroPronghorn** [comment]
Let's add a beforeDestroy or beforeUnmount and if we're tabbing out while there is text in the chatbar, store it to localstorage under an object containing a list of unfinnished notes.

**Comment by WanderingHogan** [comment]
can you try a 'git submodule update' in your repo to see if the locales conflict goes away before you make matts changes?

**Review by RetroPronghorn — APPROVED** [review]

**Comment by stavares843** [comment]
same

replies are still not appearing

Captura de ecrã 2021-12-13, às 18 52 56

**Comment by WanderingHogan** [comment]
@davidchan1219 can you open this pull request on a fresh copy of dev

**Pull request closed without merging**
