### PR TITLE
fix(nav): fix 404 on settings breadcrumb url

### PR DESCRIPTION
**Pull request by baymax-codecare**
**What this PR does** 📖
on settings modal, using breadcrumb to navigate back to chat will take the user to a broken link
**Which issue(s) this PR fixes** 🔨
AP-728

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

### CODE REVIEW

**Review by stavares843 — CHANGES_REQUESTED** [review]
Captura de ecrã 2022-02-17, às 16 26 50

when i sign up entering the app is all blank

this happens on both localhost using this branch and the netfly link

https://deploy-preview-1531--adoring-edison-dbcef8.netlify.app/#/chat/direct

Captura de ecrã 2022-02-17, às 16 27 29

**Comment by WanderingHogan** [comment]
@baymax-codecare putting this on hold until we hear back from Liz. I was looking at this and wasn't sure why we would even want these breadcrumbs working the way they are

**Comment by baymax-codecare** [comment]
@WanderingHogan @stavares843 closing this PR as I created new PR

**Pull request closed without merging**
