### PR TITLE
fix(user): fix users offline status delay

### PR DESCRIPTION
**Pull request by maljuburi**
Adds a listener for the `stopping` event for IridiumManager. to fix an offline messages issue

### CODE REVIEW

**Review by aewing — APPROVED** [review]

**Review by WanderingHogan — APPROVED** [review]

**Comment by stavares843** [comment]
Captura de ecrã 2022-09-22, às 00 23 18

and yes all PR's should point to dev and not main

**Comment by maljuburi** [comment]
closing because we decided to release on Friday 

> Captura de ecrã 2022-09-22, às 00 23 18
> 
> and yes all PR's should point to dev and not main

yes, we were on a call with Sheldon testing things in Prod.. that's why I thought we are hotfixing it :)

**Comment by stavares843** [comment]
> yes, we were on a call with Sheldon testing things in Prod.. that's why I thought we are hotfixing it :)


no, there's no hotfixing for this, we are gonna release later this week and will include all in one

**Comment by maljuburi** [comment]
> > yes, we were on a call with Sheldon testing things in Prod.. that's why I thought we are hotfixing it :)
> 
> no, there's no hotfixing for this, we are gonna release later this week and will include all in one

Yes, it was then communicated to me on Discord, but thanks

**Pull request merged**
