### PR TITLE
fix(call): dismiss incoming call when click deny button

### PR DESCRIPTION
**Pull request by genie-magic**
**What this PR does** 📖
fix(call): dismiss incoming call when click deny button

**Which issue(s) this PR fixes** 🔨

AP-524

### CODE REVIEW

**Comment by phillsatellite** [comment]
Tested: Everything worked good only issue is it seems like if friend denies call, user is unable to call them again

https://user-images.githubusercontent.com/93608357/151887436-007a7c91-42ee-4770-a146-74bddb94573a.mov

@genie-magic

**Comment by stavares843** [comment]
we should address phil's comment above

**Comment by genie-magic** [comment]
> Tested: Everything worked good only issue is it seems like if friend denies call, user is unable to call them again
> 
>  secondcall.mov 
> @genie-magic

@phillsatellite   I think about that issue, we can make separate ticket.

**Review by iltumio — APPROVED** [review]

**Review by WanderingHogan — APPROVED** [review]

**Pull request merged**
