### PR TITLE
feat(signaling): ui update to soon allow user to set signaling servers

### PR DESCRIPTION
**Pull request by WanderingHogan**
**What this PR does** 📖
These are fixes for David's PR https://github.com/Satellite-im/Core-PWA/pull/1815. This adds in a section when signing up and in settings that allows a user to change signaling servers.

This is only a UI update, and does not have any new functionality. Changing will not change the signaling servers used yet.

**Which issue(s) this PR fixes** 🔨
AP-1014

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

### CODE REVIEW

**Review by stavares843 — APPROVED** [review]

**Comment by stavares843** [comment]
feel free to merge 🎉

**Comment by molimauro** [comment]
@WanderingHogan since `pages/setup/privacy/index.vue` and `components/views/settings/pages/privacy/index.vue` have a lot in common, do you think it's a good idea to create a unique mixin for them?

**Comment by molimauro** [comment]
> @molimauro that's ideal, i didn't have time friday but I do today

Cool! With the composition API we'll forget about mixins

**Review by Jekrimo — APPROVED** [review]

**Comment by genie-magic** [comment]
@WanderingHogan  @molimauro 
I think we don't need to use mixin or composition api.. because we can use settings/privacy component in privacy setup page directly... all privacy values are stored on vuex store when changed.. so we can use them directly.  Plz review my latest changes and give me opinion. (of course privacy setup page ui is not same as before after use settings/privacy component )

**Comment by molimauro** [comment]
@genie-magic did you merge instead of rebase? There are a lot of commits, if you need help in order to fix check this doc: https://docs.google.com/document/d/1TwmuymabIoplMM58JaGU-nRjtYXNjcHC59mrj97GFxw/edit

Thank you!

**Comment by molimauro** [comment]
> > @genie-magic did you merge instead of rebase? There are a lot of commits, if you need help in order to fix check this doc: https://docs.google.com/document/d/1TwmuymabIoplMM58JaGU-nRjtYXNjcHC59mrj97GFxw/edit
> > Thank you!
> 
> I rebased and when try to push... they ask git pull first... I am not able to push until I git pull.. and this happens.

@genie-magic yes this happens because every time you rebase a branch your commits go on top of the rebased branch.

This morning you rebased so all the commits (even the ones made by hogan) went on top of dev again, thus you rewrote your local history. So now the local and the remote branch diverged. In order to correct the remote branch you have to force push, otherwise git will ask you to git pull before. You should have forced pushed, now in order to proceed you have to follow the doc instructions on how to fix the branch

**Comment by WanderingHogan** [comment]
This PR is being replaced with https://github.com/Satellite-im/Core-PWA/pull/2407

**Pull request closed without merging**
