### PR TITLE
fix(chat): typing indicator

### LINKED ISSUE #4834: typing indicator
I think there are some problems with the typing indicator:

image

Dont know how but this happened on 1to1 chat

### PR DESCRIPTION
**Pull request by molimauro**
### What this PR does 📖
- Fix typing indicator problem

### Which issue(s) this PR fixes 🔨
- Resolve #4834

### CODE REVIEW

**Comment by molimauro** [comment]
> Do we need an index check on the splice below? Only splice if >= 0. I think splice w/ -1 as index removes elements from the end

done ✅

**Review by stavares843 — COMMENTED** [review]
image



phil and I were testing and still happens seems more reproducible with pipes

**Comment by stavares843** [comment]
not against merging 😂

**Comment by molimauro** [comment]
Where is the comma between the names 😅

**Comment by stavares843** [comment]
there is none 😂 

i think that one is just pipe specific, we also had this bug even before iridium so lol

**Comment by stavares843** [comment]
not saying is from the PR, just saying we also have that one 😂

**Review by aewing — APPROVED** [review]

**Pull request merged**
