### PR TITLE
feat(jest): 97% coverage for store/friends/mutations

### PR DESCRIPTION
**Pull request by drepram**
**What this PR does** 📖

self-explanatory

**Which issue(s) this PR fixes** 🔨

AP-1387

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

### CODE REVIEW

**Comment by stavares843** [comment]
Captura de ecrã 2022-04-13, às 16 21 07

update snap pls 🔨

**Review by stavares843 — CHANGES_REQUESTED** [review]
added comment

**Comment by drepram** [comment]
Done, please check again!

**Comment by stavares843** [comment]
thanks 🎉

**Pull request merged**
