### PR TITLE
feat(profile): profile modal responsive layout AP-507

### PR DESCRIPTION
**Pull request by josephmcg**
**What this PR does** 📖
- backbone of the profile modal (fully responsive) with..
  - mock profile images (pull real data after it's added to store)
  - real user name, status, and picture
  - generic tab component (can be reused elsewhere)
- refactor UserState size so I can use large version on profile
- fix unrelated margin bug for enhancers mobile
- adjust a few css files to use breakpoint variables rather than hard coded pixel values

**Which issue(s) this PR fixes** 🔨
AP-507

**Special notes for reviewers** 🗒️
**Additional comments** 🎤

### CODE REVIEW

**Comment by stavares843** [comment]
476 is merged 🔨

**Review by WanderingHogan — APPROVED** [review]

**Comment by WanderingHogan** [comment]
In your updates today, can you move the text for tabs to locales in the same pr as the image url update

**Comment by stavares843** [comment]
Captura de ecrã 2022-01-20, às 23 50 08

this is what appears here on my side, can you share how appears on your side? @josephmcg

**Comment by WanderingHogan** [comment]
Joe will make these changes in a fresh PR

**Review by WanderingHogan — CHANGES_REQUESTED** [review]
- translations
- image url
- on mobile make the buttons line up a little better
- make the header scale better in mobile
- badge spacing on avatar
- font size on the copy
- lacking white shadow on the add icons
- icons are smaller on design
- grey line is more visible on design

**Comment by josephmcg** [comment]
- ~~translations~~
- ~~image url~~
- ~~on mobile make the buttons line up a little better~~
- make the header scale better in mobile
  - is this in reference to text? Should probably be fixed in a [heading rework](https://satellite-im.atlassian.net/browse/AP-526?filter=-4)
- ~~badge spacing on avatar~~
- ~~font size on the copy~~
  - temp fix. will improve in aforementioned typography rework
- lacking white shadow on the add icons
  - this is a component problem, not anything here. padding is being applied at the button level from bulma, meaning edges of ALL buttons will not have the glow effect.
- icons are smaller on design
  - I don't understand this one
- grey line is more visible on design
  - also a component thing. if we want to change the HR style, maybe better in another ticket. I noticed it looks bad with the other theme too, just black.

**Review by WanderingHogan — APPROVED** [review]

**Comment by WanderingHogan** [comment]
make the header scale better in mobile -> will add this to the header upload task
lacking white shadow on the add icons -> Fixed with Thomas' pr
icons are smaller on design -> Added to a research ticket, [AP-527](https://satellite-im.atlassian.net/browse/AP-527)
grey line is more visible on design -> Will be added to another ticket/and run by Liz

**Comment by stavares843** [comment]
image


minor thing with the badge to fix later

**Review by stavares843 — APPROVED** [review]

**Pull request merged**
