### PR TITLE
fix(call): mute state and reactivity

### LINKED ISSUE #4584: mute button issues - inconsistencies if you leave a call muted
mute, close call, start call again mute button shows it's muted but mute on video box doesn't show up, or you have to toggle it to stop mic feedback

### LINKED ISSUE #4768: video stream blank on first render

### PR DESCRIPTION
**Pull request by jasonwoodland**
### What this PR does 📖
- Fix call mute state when making/answering calls
- Fix MediaUser mute state indicator reactivity

### Which issue(s) this PR fixes 🔨
- Resolve #4584
- Resolve #4768

### CODE REVIEW

**Comment by josephmcg** [comment]
i see a bug where if you start a call muted (incoming or outgoing). Then unmuting has no effect, other side does not hear until you remount component

**Comment by josephmcg** [comment]
green indicator seems busted on your side if you start call muted (until remount)

**Comment by josephmcg** [comment]
Muted state seems good, but the talking indicator seems to break when toggling various streams/muted state

**Comment by molimauro** [comment]
I think this is great, better then dev for sure.. you have my vote 📝

**Pull request merged**
