### PR TITLE
fix(groupChat): all message types working in group chats

### PR DESCRIPTION
**Pull request by Jekrimo**
**What this PR does** 📖
Fixes message types available to group chats

**Which issue(s) this PR fixes** 🔨
AP-744

**Additional comments** 🎤
Some craziness happened when rebasing dev pulling in a ton of commits .

### CODE REVIEW

**Comment by stavares843** [comment]
https://github.com/Satellite-im/Core-PWA/pull/1500 - merged 🎉

**Review by iltumio — APPROVED** [review]

**Comment by WanderingHogan** [comment]
rebased cypress conflict out, otherwise the same

**Comment by phillsatellite** [comment]
Tested: Was able to send images/other file types, emojis, reactions, replies. The only thing it seemed like I wasn't able to send was Glyphs

https://user-images.githubusercontent.com/93608357/156808986-7ba33e5e-f561-48d5-a0ac-32e41a914e9a.mov

**Comment by phillsatellite** [comment]
Put temp blocked due to Groups missing from Mobile right now. Ticket is https://satellite-im.atlassian.net/jira/software/c/projects/AP/boards/5/backlog?view=detail&selectedIssue=AP-997&issueLimit=100

**Comment by stavares843** [comment]
we can check mobile later whenever that fix is ready

this changes requested is due to the glyphs bug above

**Review by stavares843 — APPROVED** [review]

**Pull request merged**
