### PR TITLE
fix(notification): clear alert number on open

### PR DESCRIPTION
**Pull request by josephmcg**
**What this PR does** 📖
- adjust notifications read indicator
- change notification unread logic

**Which issue(s) this PR fixes** 🔨
AP-1500

**Special notes for reviewers** 🗒️
this is an updated version of Jeff's PR for the same feature. I wanted to give him feedback and needed to confirm my approach would work. Since it was already done, thought it was easy to open a new PR.

We could probably add some visual indicator for brand new notifications on open in a separate ticket (or this one if you really want)

**Additional comments** 🎤

### CODE REVIEW

**Comment by Jekrimo** [comment]
Awesome! Yeah, I got the same bug, alerts would seem to clear out (leaving that space though,) but when I would send a new message, the once cleared alerts would be back

**Comment by Jekrimo** [comment]
> Awesome! Yeah, I got the same bug, alerts would seem to clear out (leaving that space though,) but when I would send a new message, the once cleared alerts would be back

I feel like maybe something didn't get caught for the push to the branch from looking through the files changes

**Comment by josephmcg** [comment]
Thank you both for checking! I will fix this tomorrow

**Comment by josephmcg** [comment]
should work more smoothly now, i cleaned up some unused mutations and actions too

**Review by phillsatellite — APPROVED** [review]

**Review by Jekrimo — APPROVED** [review]

**Review by stavares843 — APPROVED** [review]

**Pull request merged**
