### PR TITLE
chore(timestamp): implement timestamp utility

### PR DESCRIPTION
**Pull request by drepram**
### What this PR does 📖
- Replace the obsolete Vuex settings getters, and instead used the newly written timestamp utility

### Special notes for reviewers 🗒️
- There are more to be replaced. I just need to make sure that this works on other machines before I made more changes to other files 😄 

### Additional comments 🎤
-

### CODE REVIEW

**Comment by drepram** [comment]
Also, should I flag this PR as (native-android) too? The commit message is incorrect, it's not changes related to Jest 😅

**Comment by stavares843** [comment]
> Also, should I flag this PR as (native-android) too? The commit message is incorrect, it's not changes related to Jest 😅

i updated the PR title to remove the jest thing

**Review by stavares843 — COMMENTED** [review]
Captura de ecrã 2022-10-24, às 17 56 45

CI is failing building this branch

**Comment by stavares843** [comment]
is happening on any new fleek builds, team is looking into it

**Comment by josephmcg** [comment]
good so far

**Review by josephmcg — APPROVED** [review]

**Pull request merged**
