### PR TITLE
feat(ui): user update profile picture

### PR DESCRIPTION
**Pull request by baymax-codecare**
**What this PR does** 📖
in settings/profile, the user can update the profile photo.
**Which issue(s) this PR fixes** 🔨
AP-1392

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

### CODE REVIEW

**Review by Jekrimo — APPROVED** [review]

**Comment by molimauro** [comment]
Sorry @baymax-codecare why you had to implement the upload function? Wasnt that already there (the same as desktop)? The only problem i see is that on mobile you have to show it like on desktop but not implement again the same functionality

**Comment by baymax-codecare** [comment]
> Sorry @baymax-codecare why you had to implement the upload function? Wasnt that already there (the same as desktop)? The only problem i see is that on mobile you have to show it like on desktop but not implement again the same functionality

There wasn't. This problem was also happening on the desktop as well. Not implemented at all

**Review by WanderingHogan — APPROVED** [review]

**Comment by molimauro** [comment]
Ok @baymax-codecare thanks for clarifying!

**Comment by phillsatellite** [comment]
Tested: Works well but takes a pretty long time to update the profile pic, is there anyway we can speed that up at all or is it just a textile issue?

https://user-images.githubusercontent.com/93608357/164263728-70216d8a-65ba-4fe5-a4c0-03155316bb55.mov

**Review by stavares843 — APPROVED** [review]

**Pull request merged**
